#include "GameData.h"

static const CardputerGameCore::ResourceDef RESOURCES[] = {
    {"Funds", 40, 0, 999, 3, -2},
    {"Stam", 80, 0, 100, -6, 10},
    {"Supply", 25, 0, 99, -3, 4},
    {"Fear", 5, 0, 100, 4, -4},
    {"Radio", 80, 0, 100, -4, 5},
    {"Proof", 0, 0, 99, 2, 0},
    {"Expose", 0, 0, 100, 2, -2},
    {"Injury", 0, 0, 9, 1, -1},
};

static const CardputerGameCore::NamedValue CRYPTID_PARK_RANGER_ROWS_0[] = {
    {"Camper 01", "Plan camper #1: sets patrol objective"},
    {"Fence 02", "Plan fence #2: sets patrol objective"},
    {"Lights 03", "Plan lights #3: sets patrol objective"},
    {"Tracks 04", "Plan tracks #4: sets patrol objective"},
    {"Ridge 05", "Plan ridge #5: sets patrol objective"},
    {"Lake 06", "Plan lake #6: sets patrol objective"},
    {"Camper 07", "Plan camper #7: sets patrol objective"},
    {"Fence 08", "Plan fence #8: sets patrol objective"},
    {"Lights 09", "Plan lights #9: sets patrol objective"},
    {"Tracks 10", "Plan tracks #10: sets patrol objective"},
    {"Ridge 11", "Plan ridge #11: sets patrol objective"},
    {"Lake 12", "Plan lake #12: sets patrol objective"},
};

static const CardputerGameCore::NamedValue CRYPTID_PARK_RANGER_ROWS_1[] = {
    {"Forest 01", "Patrol forest #1: applies zone danger"},
    {"Lake 02", "Patrol lake #2: applies zone danger"},
    {"Ridge 03", "Patrol ridge #3: applies zone danger"},
    {"Cave 04", "Patrol cave #4: applies zone danger"},
    {"Camp 05", "Patrol camp #5: applies zone danger"},
    {"Road 06", "Patrol road #6: applies zone danger"},
    {"Bog 07", "Patrol bog #7: applies zone danger"},
    {"Summit 08", "Patrol summit #8: applies zone danger"},
    {"Lodge 09", "Patrol lodge #9: applies zone danger"},
    {"Preserve 10", "Patrol preserve #10: applies zone danger"},
};

static const CardputerGameCore::NamedValue CRYPTID_PARK_RANGER_ROWS_2[] = {
    {"Camera 01", "Pack camera #1: sets evidence bonus"},
    {"Bait 02", "Pack bait #2: sets evidence bonus"},
    {"Recorder 03", "Pack recorder #3: sets evidence bonus"},
    {"Sample Kit 04", "Pack sample kit #4: sets evidence bonus"},
    {"Thermal 05", "Pack thermal #5: sets evidence bonus"},
    {"Medkit 06", "Pack medkit #6: sets evidence bonus"},
    {"Rope 07", "Pack rope #7: sets evidence bonus"},
    {"Battery 08", "Pack battery #8: sets evidence bonus"},
};

static const CardputerGameCore::NamedValue CRYPTID_PARK_RANGER_ROWS_3[] = {
    {"Print 01", "Decide print #1: raises evidence meters"},
    {"Photo 02", "Decide photo #2: raises evidence meters"},
    {"Audio 03", "Decide audio #3: raises evidence meters"},
    {"Sample 04", "Decide sample #4: raises evidence meters"},
    {"Sighting 05", "Decide sighting #5: raises evidence meters"},
    {"Print 06", "Decide print #6: raises evidence meters"},
    {"Photo 07", "Decide photo #7: raises evidence meters"},
    {"Audio 08", "Decide audio #8: raises evidence meters"},
    {"Sample 09", "Decide sample #9: raises evidence meters"},
    {"Sighting 10", "Decide sighting #10: raises evidence meters"},
    {"Print 11", "Decide print #11: raises evidence meters"},
    {"Photo 12", "Decide photo #12: raises evidence meters"},
    {"Audio 13", "Decide audio #13: raises evidence meters"},
    {"Sample 14", "Decide sample #14: raises evidence meters"},
    {"Sighting 15", "Decide sighting #15: raises evidence meters"},
    {"Print 16", "Decide print #16: raises evidence meters"},
    {"Photo 17", "Decide photo #17: raises evidence meters"},
    {"Audio 18", "Decide audio #18: raises evidence meters"},
    {"Sample 19", "Decide sample #19: raises evidence meters"},
    {"Sighting 20", "Decide sighting #20: raises evidence meters"},
};

static const CardputerGameCore::NamedValue CRYPTID_PARK_RANGER_ROWS_4[] = {
    {"Mossback 01", "Study mossback #1: reveals ethical notes"},
    {"Lake Wisp 02", "Study lake wisp #2: reveals ethical notes"},
    {"Ridge Antler 03", "Study ridge antler #3: reveals ethical notes"},
    {"Cave Mute 04", "Study cave mute #4: reveals ethical notes"},
    {"Ash Cat 05", "Study ash cat #5: reveals ethical notes"},
    {"Bog Lamp 06", "Study bog lamp #6: reveals ethical notes"},
    {"Summit Moth 07", "Study summit moth #7: reveals ethical notes"},
    {"Pine Crown 08", "Study pine crown #8: reveals ethical notes"},
    {"Mossback 09", "Study mossback #9: reveals ethical notes"},
    {"Lake Wisp 10", "Study lake wisp #10: reveals ethical notes"},
    {"Ridge Antler 11", "Study ridge antler #11: reveals ethical notes"},
    {"Cave Mute 12", "Study cave mute #12: reveals ethical notes"},
    {"Ash Cat 13", "Study ash cat #13: reveals ethical notes"},
    {"Bog Lamp 14", "Study bog lamp #14: reveals ethical notes"},
    {"Summit Moth 15", "Study summit moth #15: reveals ethical notes"},
    {"Pine Crown 16", "Study pine crown #16: reveals ethical notes"},
};

static const CardputerGameCore::NamedValue CRYPTID_PARK_RANGER_ROWS_5[] = {
    {"Missing Camper 01", "Resolve missing camper #1: closes ranger calls"},
    {"Fence Break 02", "Resolve fence break #2: closes ranger calls"},
    {"Odd Lights 03", "Resolve odd lights #3: closes ranger calls"},
    {"Injured Animal 04", "Resolve injured animal #4: closes ranger calls"},
    {"Sponsor 05", "Resolve sponsor #5: closes ranger calls"},
    {"Research 06", "Resolve research #6: closes ranger calls"},
    {"Missing Camper 07", "Resolve missing camper #7: closes ranger calls"},
    {"Fence Break 08", "Resolve fence break #8: closes ranger calls"},
    {"Odd Lights 09", "Resolve odd lights #9: closes ranger calls"},
    {"Injured Animal 10", "Resolve injured animal #10: closes ranger calls"},
    {"Sponsor 11", "Resolve sponsor #11: closes ranger calls"},
    {"Research 12", "Resolve research #12: closes ranger calls"},
};

static const CardputerGameCore::NamedValue CRYPTID_PARK_RANGER_ROWS_6[] = {
    {"Clue 01", "Handle clue #1: changes proof and risk"},
    {"Weather 02", "Handle weather #2: changes proof and risk"},
    {"Rescue 03", "Handle rescue #3: changes proof and risk"},
    {"Ethics 04", "Handle ethics #4: changes proof and risk"},
    {"Sponsor 05", "Handle sponsor #5: changes proof and risk"},
    {"Rare 06", "Handle rare #6: changes proof and risk"},
    {"Camp 07", "Handle camp #7: changes proof and risk"},
    {"Night 08", "Handle night #8: changes proof and risk"},
    {"Clue 09", "Handle clue #9: changes proof and risk"},
    {"Weather 10", "Handle weather #10: changes proof and risk"},
    {"Rescue 11", "Handle rescue #11: changes proof and risk"},
    {"Ethics 12", "Handle ethics #12: changes proof and risk"},
    {"Sponsor 13", "Handle sponsor #13: changes proof and risk"},
    {"Rare 14", "Handle rare #14: changes proof and risk"},
    {"Camp 15", "Handle camp #15: changes proof and risk"},
    {"Night 16", "Handle night #16: changes proof and risk"},
    {"Clue 17", "Handle clue #17: changes proof and risk"},
    {"Weather 18", "Handle weather #18: changes proof and risk"},
    {"Rescue 19", "Handle rescue #19: changes proof and risk"},
    {"Ethics 20", "Handle ethics #20: changes proof and risk"},
    {"Sponsor 21", "Handle sponsor #21: changes proof and risk"},
    {"Rare 22", "Handle rare #22: changes proof and risk"},
    {"Camp 23", "Handle camp #23: changes proof and risk"},
    {"Night 24", "Handle night #24: changes proof and risk"},
    {"Clue 25", "Handle clue #25: changes proof and risk"},
    {"Weather 26", "Handle weather #26: changes proof and risk"},
    {"Rescue 27", "Handle rescue #27: changes proof and risk"},
    {"Ethics 28", "Handle ethics #28: changes proof and risk"},
    {"Sponsor 29", "Handle sponsor #29: changes proof and risk"},
    {"Rare 30", "Handle rare #30: changes proof and risk"},
    {"Camp 31", "Handle camp #31: changes proof and risk"},
    {"Night 32", "Handle night #32: changes proof and risk"},
    {"Clue 33", "Handle clue #33: changes proof and risk"},
    {"Weather 34", "Handle weather #34: changes proof and risk"},
    {"Rescue 35", "Handle rescue #35: changes proof and risk"},
    {"Ethics 36", "Handle ethics #36: changes proof and risk"},
    {"Sponsor 37", "Handle sponsor #37: changes proof and risk"},
    {"Rare 38", "Handle rare #38: changes proof and risk"},
    {"Camp 39", "Handle camp #39: changes proof and risk"},
    {"Night 40", "Handle night #40: changes proof and risk"},
    {"Clue 41", "Handle clue #41: changes proof and risk"},
    {"Weather 42", "Handle weather #42: changes proof and risk"},
    {"Rescue 43", "Handle rescue #43: changes proof and risk"},
    {"Ethics 44", "Handle ethics #44: changes proof and risk"},
    {"Sponsor 45", "Handle sponsor #45: changes proof and risk"},
    {"Rare 46", "Handle rare #46: changes proof and risk"},
    {"Camp 47", "Handle camp #47: changes proof and risk"},
    {"Night 48", "Handle night #48: changes proof and risk"},
};

static const CardputerGameCore::DeepScreenDef SCREENS[] = {
    {"STATION", "Plan", CRYPTID_PARK_RANGER_ROWS_0, 12, {1, 4, 1, -2, 2, 1, -1, -1}, 3, 0, 1UL},
    {"ZONES", "Patrol", CRYPTID_PARK_RANGER_ROWS_1, 10, {2, -6, -3, 3, -4, 2, 2, 1}, 5, 1, 2UL},
    {"GEAR", "Pack", CRYPTID_PARK_RANGER_ROWS_2, 8, {-3, 1, 2, -1, 2, 1, -1, -1}, 3, 2, 4UL},
    {"TRACK", "Decide", CRYPTID_PARK_RANGER_ROWS_3, 20, {2, -2, -1, 2, -2, 3, 1, 0}, 5, 3, 8UL},
    {"GUIDE", "Study", CRYPTID_PARK_RANGER_ROWS_4, 16, {0, 0, 1, -1, 0, 2, -1, 0}, 3, 4, 16UL},
    {"REPORTS", "Resolve", CRYPTID_PARK_RANGER_ROWS_5, 12, {4, -2, -2, 1, -1, 3, -2, -1}, 5, 5, 32UL},
    {"EVENTS", "Handle", CRYPTID_PARK_RANGER_ROWS_6, 48, {2, -4, -3, 4, -3, 2, 2, 1}, 4, 6, 64UL},
};

static const CardputerGameCore::NamedValue EVENTS[] = {
    {"Pressure 01", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Choice 02", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Discovery 03", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Trouble 04", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Favor 05", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Warning 06", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Breakthrough 07", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Setback 08", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Pressure 09", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Choice 10", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Discovery 11", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Trouble 12", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Favor 13", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Warning 14", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Breakthrough 15", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Setback 16", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Pressure 17", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Choice 18", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Discovery 19", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Trouble 20", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Favor 21", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Warning 22", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Breakthrough 23", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Setback 24", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Pressure 25", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Choice 26", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Discovery 27", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Trouble 28", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Favor 29", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Warning 30", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Breakthrough 31", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Setback 32", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Pressure 33", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Choice 34", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Discovery 35", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Trouble 36", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Favor 37", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Warning 38", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Breakthrough 39", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Setback 40", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Pressure 41", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Choice 42", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Discovery 43", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Trouble 44", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Favor 45", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Warning 46", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Breakthrough 47", "A bespoke Cryptid Ranger event changes saved state and story flags."},
    {"Setback 48", "A bespoke Cryptid Ranger event changes saved state and story flags."},
};

static const CardputerGameCore::NamedValue ENDINGS[] = {
    {"Science Guide", "Ending path 1: resources, flags, and reputation decide this outcome."},
    {"Park Guardian", "Ending path 2: resources, flags, and reputation decide this outcome."},
    {"Town Legend", "Ending path 3: resources, flags, and reputation decide this outcome."},
    {"Mystery Solved", "Ending path 4: resources, flags, and reputation decide this outcome."},
    {"Ethics Breach", "Ending path 5: resources, flags, and reputation decide this outcome."},
    {"Lost Patrol", "Ending path 6: resources, flags, and reputation decide this outcome."},
};

static const CardputerGameCore::DeepGameDefinition DEF = {
    "Cryptid Ranger",
    "cryptid-park-ranger",
    "Ethical field research",
    "CPR2",
    RESOURCES,
    sizeof(RESOURCES) / sizeof(RESOURCES[0]),
    SCREENS,
    sizeof(SCREENS) / sizeof(SCREENS[0]),
    EVENTS,
    sizeof(EVENTS) / sizeof(EVENTS[0]),
    ENDINGS,
    sizeof(ENDINGS) / sizeof(ENDINGS[0]),
    170,
    0x07E0,
    0xFD20
};

const CardputerGameCore::DeepGameDefinition& gameDefinition() {
  return DEF;
}
