#include "GameData.h"

static const CardputerGameCore::ResourceDef RESOURCES[] = {
    {"Food", 65, 0, 999, -4, 7},
    {"Water", 60, 0, 999, -5, 7},
    {"Meds", 5, 0, 99, -1, 1},
    {"Ammo", 18, 0, 99, -2, 1},
    {"Scrap", 25, 0, 999, 4, -1},
    {"Power", 35, 0, 120, -3, 3},
    {"Mor", 70, 0, 100, -2, 5},
    {"Def", 20, 0, 100, 1, 1},
};

static const CardputerGameCore::NamedValue WASTELAND_GUILDMASTER_ROWS_0[] = {
    {"Food 01", "Command food #1: checks settlement pressure"},
    {"Water 02", "Command water #2: checks settlement pressure"},
    {"Clinic 03", "Command clinic #3: checks settlement pressure"},
    {"Tower 04", "Command tower #4: checks settlement pressure"},
    {"Farm 05", "Command farm #5: checks settlement pressure"},
    {"Depot 06", "Command depot #6: checks settlement pressure"},
    {"Food 07", "Command food #7: checks settlement pressure"},
    {"Water 08", "Command water #8: checks settlement pressure"},
    {"Clinic 09", "Command clinic #9: checks settlement pressure"},
    {"Tower 10", "Command tower #10: checks settlement pressure"},
    {"Farm 11", "Command farm #11: checks settlement pressure"},
    {"Depot 12", "Command depot #12: checks settlement pressure"},
};

static const CardputerGameCore::NamedValue WASTELAND_GUILDMASTER_ROWS_1[] = {
    {"Clinic 01", "Launch clinic #1: sends a team for loot"},
    {"Tower 02", "Launch tower #2: sends a team for loot"},
    {"Depot 03", "Launch depot #3: sends a team for loot"},
    {"Tunnel 04", "Launch tunnel #4: sends a team for loot"},
    {"Farm 05", "Launch farm #5: sends a team for loot"},
    {"Storm 06", "Launch storm #6: sends a team for loot"},
    {"River 07", "Launch river #7: sends a team for loot"},
    {"Authority 08", "Launch authority #8: sends a team for loot"},
    {"Clinic 09", "Launch clinic #9: sends a team for loot"},
    {"Tower 10", "Launch tower #10: sends a team for loot"},
    {"Depot 11", "Launch depot #11: sends a team for loot"},
    {"Tunnel 12", "Launch tunnel #12: sends a team for loot"},
    {"Farm 13", "Launch farm #13: sends a team for loot"},
    {"Storm 14", "Launch storm #14: sends a team for loot"},
    {"River 15", "Launch river #15: sends a team for loot"},
    {"Authority 16", "Launch authority #16: sends a team for loot"},
    {"Clinic 17", "Launch clinic #17: sends a team for loot"},
    {"Tower 18", "Launch tower #18: sends a team for loot"},
    {"Depot 19", "Launch depot #19: sends a team for loot"},
    {"Tunnel 20", "Launch tunnel #20: sends a team for loot"},
    {"Farm 21", "Launch farm #21: sends a team for loot"},
    {"Storm 22", "Launch storm #22: sends a team for loot"},
    {"River 23", "Launch river #23: sends a team for loot"},
    {"Authority 24", "Launch authority #24: sends a team for loot"},
};

static const CardputerGameCore::NamedValue WASTELAND_GUILDMASTER_ROWS_2[] = {
    {"Scout 01", "Assign scout #1: changes stage odds"},
    {"Medic 02", "Assign medic #2: changes stage odds"},
    {"Guard 03", "Assign guard #3: changes stage odds"},
    {"Tech 04", "Assign tech #4: changes stage odds"},
    {"Cook 05", "Assign cook #5: changes stage odds"},
    {"Baron 06", "Assign baron #6: changes stage odds"},
    {"Cultist 07", "Assign cultist #7: changes stage odds"},
    {"Radio 08", "Assign radio #8: changes stage odds"},
};

static const CardputerGameCore::NamedValue WASTELAND_GUILDMASTER_ROWS_3[] = {
    {"Ruin 01", "Resolve ruin #1: applies role checks and moral pressure"},
    {"Clinic 02", "Resolve clinic #2: applies role checks and moral pressure"},
    {"Depot 03", "Resolve depot #3: applies role checks and moral pressure"},
    {"Tower 04", "Resolve tower #4: applies role checks and moral pressure"},
    {"Farm 05", "Resolve farm #5: applies role checks and moral pressure"},
    {"Tunnel 06", "Resolve tunnel #6: applies role checks and moral pressure"},
    {"Camp 07", "Resolve camp #7: applies role checks and moral pressure"},
    {"Signal 08", "Resolve signal #8: applies role checks and moral pressure"},
    {"Ruin 09", "Resolve ruin #9: applies role checks and moral pressure"},
    {"Clinic 10", "Resolve clinic #10: applies role checks and moral pressure"},
    {"Depot 11", "Resolve depot #11: applies role checks and moral pressure"},
    {"Tower 12", "Resolve tower #12: applies role checks and moral pressure"},
    {"Farm 13", "Resolve farm #13: applies role checks and moral pressure"},
    {"Tunnel 14", "Resolve tunnel #14: applies role checks and moral pressure"},
    {"Camp 15", "Resolve camp #15: applies role checks and moral pressure"},
    {"Signal 16", "Resolve signal #16: applies role checks and moral pressure"},
    {"Ruin 17", "Resolve ruin #17: applies role checks and moral pressure"},
    {"Clinic 18", "Resolve clinic #18: applies role checks and moral pressure"},
    {"Depot 19", "Resolve depot #19: applies role checks and moral pressure"},
    {"Tower 20", "Resolve tower #20: applies role checks and moral pressure"},
    {"Farm 21", "Resolve farm #21: applies role checks and moral pressure"},
    {"Tunnel 22", "Resolve tunnel #22: applies role checks and moral pressure"},
    {"Camp 23", "Resolve camp #23: applies role checks and moral pressure"},
    {"Signal 24", "Resolve signal #24: applies role checks and moral pressure"},
    {"Ruin 25", "Resolve ruin #25: applies role checks and moral pressure"},
    {"Clinic 26", "Resolve clinic #26: applies role checks and moral pressure"},
    {"Depot 27", "Resolve depot #27: applies role checks and moral pressure"},
    {"Tower 28", "Resolve tower #28: applies role checks and moral pressure"},
    {"Farm 29", "Resolve farm #29: applies role checks and moral pressure"},
    {"Tunnel 30", "Resolve tunnel #30: applies role checks and moral pressure"},
    {"Camp 31", "Resolve camp #31: applies role checks and moral pressure"},
    {"Signal 32", "Resolve signal #32: applies role checks and moral pressure"},
    {"Ruin 33", "Resolve ruin #33: applies role checks and moral pressure"},
    {"Clinic 34", "Resolve clinic #34: applies role checks and moral pressure"},
    {"Depot 35", "Resolve depot #35: applies role checks and moral pressure"},
    {"Tower 36", "Resolve tower #36: applies role checks and moral pressure"},
};

static const CardputerGameCore::NamedValue WASTELAND_GUILDMASTER_ROWS_4[] = {
    {"Garden 01", "Build garden #1: spends scrap and power"},
    {"Purifier 02", "Build purifier #2: spends scrap and power"},
    {"Clinic 03", "Build clinic #3: spends scrap and power"},
    {"Workshop 04", "Build workshop #4: spends scrap and power"},
    {"Barracks 05", "Build barracks #5: spends scrap and power"},
    {"Watchtower 06", "Build watchtower #6: spends scrap and power"},
    {"Radio 07", "Build radio #7: spends scrap and power"},
    {"School 08", "Build school #8: spends scrap and power"},
    {"Walls 09", "Build walls #9: spends scrap and power"},
    {"Storage 10", "Build storage #10: spends scrap and power"},
    {"Garden 11", "Build garden #11: spends scrap and power"},
    {"Purifier 12", "Build purifier #12: spends scrap and power"},
    {"Clinic 13", "Build clinic #13: spends scrap and power"},
    {"Workshop 14", "Build workshop #14: spends scrap and power"},
    {"Barracks 15", "Build barracks #15: spends scrap and power"},
    {"Watchtower 16", "Build watchtower #16: spends scrap and power"},
    {"Radio 17", "Build radio #17: spends scrap and power"},
    {"School 18", "Build school #18: spends scrap and power"},
    {"Walls 19", "Build walls #19: spends scrap and power"},
    {"Storage 20", "Build storage #20: spends scrap and power"},
    {"Garden 21", "Build garden #21: spends scrap and power"},
    {"Purifier 22", "Build purifier #22: spends scrap and power"},
    {"Clinic 23", "Build clinic #23: spends scrap and power"},
    {"Workshop 24", "Build workshop #24: spends scrap and power"},
    {"Barracks 25", "Build barracks #25: spends scrap and power"},
    {"Watchtower 26", "Build watchtower #26: spends scrap and power"},
    {"Radio 27", "Build radio #27: spends scrap and power"},
    {"School 28", "Build school #28: spends scrap and power"},
    {"Walls 29", "Build walls #29: spends scrap and power"},
    {"Storage 30", "Build storage #30: spends scrap and power"},
};

static const CardputerGameCore::NamedValue WASTELAND_GUILDMASTER_ROWS_5[] = {
    {"Raiders 01", "Answer raiders #1: resolves settlement clocks"},
    {"Sickness 02", "Answer sickness #2: resolves settlement clocks"},
    {"Storm 03", "Answer storm #3: resolves settlement clocks"},
    {"Hunger 04", "Answer hunger #4: resolves settlement clocks"},
    {"Demand 05", "Answer demand #5: resolves settlement clocks"},
    {"Raiders 06", "Answer raiders #6: resolves settlement clocks"},
    {"Sickness 07", "Answer sickness #7: resolves settlement clocks"},
    {"Storm 08", "Answer storm #8: resolves settlement clocks"},
    {"Hunger 09", "Answer hunger #9: resolves settlement clocks"},
    {"Demand 10", "Answer demand #10: resolves settlement clocks"},
    {"Raiders 11", "Answer raiders #11: resolves settlement clocks"},
    {"Sickness 12", "Answer sickness #12: resolves settlement clocks"},
    {"Storm 13", "Answer storm #13: resolves settlement clocks"},
    {"Hunger 14", "Answer hunger #14: resolves settlement clocks"},
    {"Demand 15", "Answer demand #15: resolves settlement clocks"},
    {"Raiders 16", "Answer raiders #16: resolves settlement clocks"},
    {"Sickness 17", "Answer sickness #17: resolves settlement clocks"},
    {"Storm 18", "Answer storm #18: resolves settlement clocks"},
    {"Hunger 19", "Answer hunger #19: resolves settlement clocks"},
    {"Demand 20", "Answer demand #20: resolves settlement clocks"},
};

static const CardputerGameCore::DeepScreenDef SCREENS[] = {
    {"BASE", "Command", WASTELAND_GUILDMASTER_ROWS_0, 12, {-3, -3, -1, -1, 2, -1, 2, 1}, 3, 0, 1UL},
    {"MISSIONS", "Launch", WASTELAND_GUILDMASTER_ROWS_1, 24, {3, 2, 2, -2, 5, -2, -1, 1}, 5, 1, 2UL},
    {"TEAM", "Assign", WASTELAND_GUILDMASTER_ROWS_2, 8, {-1, -1, 1, 1, -1, 1, 2, 1}, 3, 2, 4UL},
    {"RESULT", "Resolve", WASTELAND_GUILDMASTER_ROWS_3, 36, {4, 2, 1, -2, 3, -1, -2, 1}, 5, 3, 8UL},
    {"BUILD", "Build", WASTELAND_GUILDMASTER_ROWS_4, 30, {3, 3, 1, 1, -8, -4, 2, 4}, 5, 4, 16UL},
    {"THREATS", "Answer", WASTELAND_GUILDMASTER_ROWS_5, 20, {-4, -4, -2, -2, 2, -2, -4, 2}, 4, 5, 32UL},
};

static const CardputerGameCore::NamedValue EVENTS[] = {
    {"Pressure 01", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Choice 02", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Discovery 03", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Trouble 04", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Favor 05", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Warning 06", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Breakthrough 07", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Setback 08", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Pressure 09", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Choice 10", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Discovery 11", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Trouble 12", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Favor 13", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Warning 14", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Breakthrough 15", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Setback 16", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Pressure 17", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Choice 18", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Discovery 19", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Trouble 20", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Favor 21", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Warning 22", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Breakthrough 23", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Setback 24", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Pressure 25", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Choice 26", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Discovery 27", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Trouble 28", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Favor 29", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Warning 30", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Breakthrough 31", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Setback 32", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Pressure 33", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Choice 34", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Discovery 35", "A bespoke Waste Guild event changes saved state and story flags."},
    {"Trouble 36", "A bespoke Waste Guild event changes saved state and story flags."},
};

static const CardputerGameCore::NamedValue ENDINGS[] = {
    {"Fortress Town", "Ending path 1: resources, flags, and reputation decide this outcome."},
    {"Mobile Convoy", "Ending path 2: resources, flags, and reputation decide this outcome."},
    {"River Alliance", "Ending path 3: resources, flags, and reputation decide this outcome."},
    {"Signal Beacon", "Ending path 4: resources, flags, and reputation decide this outcome."},
    {"Bunker Rule", "Ending path 5: resources, flags, and reputation decide this outcome."},
    {"Camp Collapse", "Ending path 6: resources, flags, and reputation decide this outcome."},
};

static const CardputerGameCore::DeepGameDefinition DEF = {
    "Waste Guild",
    "wasteland-guildmaster",
    "Settlement command sim",
    "WGM2",
    RESOURCES,
    sizeof(RESOURCES) / sizeof(RESOURCES[0]),
    SCREENS,
    sizeof(SCREENS) / sizeof(SCREENS[0]),
    EVENTS,
    sizeof(EVENTS) / sizeof(EVENTS[0]),
    ENDINGS,
    sizeof(ENDINGS) / sizeof(ENDINGS[0]),
    175,
    0xFD20,
    0xFD20
};

const CardputerGameCore::DeepGameDefinition& gameDefinition() {
  return DEF;
}
