#include "GameData.h"

static const CardputerGameCore::ResourceDef RESOURCES[] = {
    {"Food", 80, 0, 999, 3, 5},
    {"Gold", 55, 0, 999, 4, -2},
    {"Wood", 35, 0, 999, 2, 0},
    {"Pop", 40, 0, 200, 1, 1},
    {"Sold", 8, 0, 100, 1, 0},
    {"Mor", 70, 0, 100, -2, 4},
    {"Faith", 25, 0, 100, 1, 1},
    {"Threat", 10, 0, 100, 4, -3},
};

static const CardputerGameCore::NamedValue POCKET_KINGDOM_MANAGER_ROWS_0[] = {
    {"Spring 01", "Rule spring #1: sets seasonal pressure"},
    {"Summer 02", "Rule summer #2: sets seasonal pressure"},
    {"Autumn 03", "Rule autumn #3: sets seasonal pressure"},
    {"Winter 04", "Rule winter #4: sets seasonal pressure"},
    {"Spring 05", "Rule spring #5: sets seasonal pressure"},
    {"Summer 06", "Rule summer #6: sets seasonal pressure"},
    {"Autumn 07", "Rule autumn #7: sets seasonal pressure"},
    {"Winter 08", "Rule winter #8: sets seasonal pressure"},
    {"Spring 09", "Rule spring #9: sets seasonal pressure"},
    {"Summer 10", "Rule summer #10: sets seasonal pressure"},
    {"Autumn 11", "Rule autumn #11: sets seasonal pressure"},
    {"Winter 12", "Rule winter #12: sets seasonal pressure"},
    {"Spring 13", "Rule spring #13: sets seasonal pressure"},
    {"Summer 14", "Rule summer #14: sets seasonal pressure"},
    {"Autumn 15", "Rule autumn #15: sets seasonal pressure"},
    {"Winter 16", "Rule winter #16: sets seasonal pressure"},
};

static const CardputerGameCore::NamedValue POCKET_KINGDOM_MANAGER_ROWS_1[] = {
    {"Farm 01", "Assign farm #1: moves population into work"},
    {"Mine 02", "Assign mine #2: moves population into work"},
    {"Wall 03", "Assign wall #3: moves population into work"},
    {"Temple 04", "Assign temple #4: moves population into work"},
    {"Market 05", "Assign market #5: moves population into work"},
    {"Study 06", "Assign study #6: moves population into work"},
    {"Army 07", "Assign army #7: moves population into work"},
};

static const CardputerGameCore::NamedValue POCKET_KINGDOM_MANAGER_ROWS_2[] = {
    {"Farm 01", "Upgrade farm #1: spends gold and wood for a level"},
    {"Granary 02", "Upgrade granary #2: spends gold and wood for a level"},
    {"Barracks 03", "Upgrade barracks #3: spends gold and wood for a level"},
    {"Wall 04", "Upgrade wall #4: spends gold and wood for a level"},
    {"Market 05", "Upgrade market #5: spends gold and wood for a level"},
    {"Shrine 06", "Upgrade shrine #6: spends gold and wood for a level"},
    {"Library 07", "Upgrade library #7: spends gold and wood for a level"},
    {"Tower 08", "Upgrade tower #8: spends gold and wood for a level"},
    {"Roads 09", "Upgrade roads #9: spends gold and wood for a level"},
    {"Infirmary 10", "Upgrade infirmary #10: spends gold and wood for a level"},
    {"Farm 11", "Upgrade farm #11: spends gold and wood for a level"},
    {"Granary 12", "Upgrade granary #12: spends gold and wood for a level"},
    {"Barracks 13", "Upgrade barracks #13: spends gold and wood for a level"},
    {"Wall 14", "Upgrade wall #14: spends gold and wood for a level"},
    {"Market 15", "Upgrade market #15: spends gold and wood for a level"},
    {"Shrine 16", "Upgrade shrine #16: spends gold and wood for a level"},
    {"Library 17", "Upgrade library #17: spends gold and wood for a level"},
    {"Tower 18", "Upgrade tower #18: spends gold and wood for a level"},
    {"Roads 19", "Upgrade roads #19: spends gold and wood for a level"},
    {"Infirmary 20", "Upgrade infirmary #20: spends gold and wood for a level"},
    {"Farm 21", "Upgrade farm #21: spends gold and wood for a level"},
    {"Granary 22", "Upgrade granary #22: spends gold and wood for a level"},
    {"Barracks 23", "Upgrade barracks #23: spends gold and wood for a level"},
    {"Wall 24", "Upgrade wall #24: spends gold and wood for a level"},
    {"Market 25", "Upgrade market #25: spends gold and wood for a level"},
    {"Shrine 26", "Upgrade shrine #26: spends gold and wood for a level"},
    {"Library 27", "Upgrade library #27: spends gold and wood for a level"},
    {"Tower 28", "Upgrade tower #28: spends gold and wood for a level"},
    {"Roads 29", "Upgrade roads #29: spends gold and wood for a level"},
    {"Infirmary 30", "Upgrade infirmary #30: spends gold and wood for a level"},
};

static const CardputerGameCore::NamedValue POCKET_KINGDOM_MANAGER_ROWS_3[] = {
    {"Tax 01", "Pass tax #1: alters factions and crisis flags"},
    {"Bread 02", "Pass bread #2: alters factions and crisis flags"},
    {"Militia 03", "Pass militia #3: alters factions and crisis flags"},
    {"Tithe 04", "Pass tithe #4: alters factions and crisis flags"},
    {"Trade 05", "Pass trade #5: alters factions and crisis flags"},
    {"School 06", "Pass school #6: alters factions and crisis flags"},
    {"Curfew 07", "Pass curfew #7: alters factions and crisis flags"},
    {"Water 08", "Pass water #8: alters factions and crisis flags"},
    {"Inheritance 09", "Pass inheritance #9: alters factions and crisis flags"},
    {"Charter 10", "Pass charter #10: alters factions and crisis flags"},
    {"Magic 11", "Pass magic #11: alters factions and crisis flags"},
    {"Relief 12", "Pass relief #12: alters factions and crisis flags"},
};

static const CardputerGameCore::NamedValue POCKET_KINGDOM_MANAGER_ROWS_4[] = {
    {"Steward 01", "Hear steward #1: shifts reputation and risk"},
    {"Marshal 02", "Hear marshal #2: shifts reputation and risk"},
    {"Priest 03", "Hear priest #3: shifts reputation and risk"},
    {"Mage 04", "Hear mage #4: shifts reputation and risk"},
    {"Noble 05", "Hear noble #5: shifts reputation and risk"},
    {"Farmer 06", "Hear farmer #6: shifts reputation and risk"},
    {"Heir 07", "Hear heir #7: shifts reputation and risk"},
    {"Envoy 08", "Hear envoy #8: shifts reputation and risk"},
    {"Judge 09", "Hear judge #9: shifts reputation and risk"},
    {"Scribe 10", "Hear scribe #10: shifts reputation and risk"},
};

static const CardputerGameCore::NamedValue POCKET_KINGDOM_MANAGER_ROWS_5[] = {
    {"Famine 01", "Answer famine #1: spends resources or creates a chain"},
    {"Raid 02", "Answer raid #2: spends resources or creates a chain"},
    {"Plague 03", "Answer plague #3: spends resources or creates a chain"},
    {"Scandal 04", "Answer scandal #4: spends resources or creates a chain"},
    {"Petition 05", "Answer petition #5: spends resources or creates a chain"},
    {"Festival 06", "Answer festival #6: spends resources or creates a chain"},
    {"Succession 07", "Answer succession #7: spends resources or creates a chain"},
    {"Magic Leak 08", "Answer magic leak #8: spends resources or creates a chain"},
    {"Famine 09", "Answer famine #9: spends resources or creates a chain"},
    {"Raid 10", "Answer raid #10: spends resources or creates a chain"},
    {"Plague 11", "Answer plague #11: spends resources or creates a chain"},
    {"Scandal 12", "Answer scandal #12: spends resources or creates a chain"},
    {"Petition 13", "Answer petition #13: spends resources or creates a chain"},
    {"Festival 14", "Answer festival #14: spends resources or creates a chain"},
    {"Succession 15", "Answer succession #15: spends resources or creates a chain"},
    {"Magic Leak 16", "Answer magic leak #16: spends resources or creates a chain"},
    {"Famine 17", "Answer famine #17: spends resources or creates a chain"},
    {"Raid 18", "Answer raid #18: spends resources or creates a chain"},
    {"Plague 19", "Answer plague #19: spends resources or creates a chain"},
    {"Scandal 20", "Answer scandal #20: spends resources or creates a chain"},
    {"Petition 21", "Answer petition #21: spends resources or creates a chain"},
    {"Festival 22", "Answer festival #22: spends resources or creates a chain"},
    {"Succession 23", "Answer succession #23: spends resources or creates a chain"},
    {"Magic Leak 24", "Answer magic leak #24: spends resources or creates a chain"},
    {"Famine 25", "Answer famine #25: spends resources or creates a chain"},
    {"Raid 26", "Answer raid #26: spends resources or creates a chain"},
    {"Plague 27", "Answer plague #27: spends resources or creates a chain"},
    {"Scandal 28", "Answer scandal #28: spends resources or creates a chain"},
    {"Petition 29", "Answer petition #29: spends resources or creates a chain"},
    {"Festival 30", "Answer festival #30: spends resources or creates a chain"},
    {"Succession 31", "Answer succession #31: spends resources or creates a chain"},
    {"Magic Leak 32", "Answer magic leak #32: spends resources or creates a chain"},
    {"Famine 33", "Answer famine #33: spends resources or creates a chain"},
    {"Raid 34", "Answer raid #34: spends resources or creates a chain"},
    {"Plague 35", "Answer plague #35: spends resources or creates a chain"},
    {"Scandal 36", "Answer scandal #36: spends resources or creates a chain"},
};

static const CardputerGameCore::NamedValue POCKET_KINGDOM_MANAGER_ROWS_6[] = {
    {"Harvest 01", "Close harvest #1: summarizes dynasty progress"},
    {"Border 02", "Close border #2: summarizes dynasty progress"},
    {"Faith 03", "Close faith #3: summarizes dynasty progress"},
    {"Mage 04", "Close mage #4: summarizes dynasty progress"},
    {"People 05", "Close people #5: summarizes dynasty progress"},
    {"Nobles 06", "Close nobles #6: summarizes dynasty progress"},
    {"Heir 07", "Close heir #7: summarizes dynasty progress"},
    {"Dragon 08", "Close dragon #8: summarizes dynasty progress"},
};

static const CardputerGameCore::DeepScreenDef SCREENS[] = {
    {"REALM", "Review", POCKET_KINGDOM_MANAGER_ROWS_0, 16, {2, 1, 1, 1, 0, 1, 1, 1}, 3, 0, 1UL},
    {"WORK", "Assign", POCKET_KINGDOM_MANAGER_ROWS_1, 7, {5, 3, 3, 0, 1, -1, 1, -2}, 4, 1, 2UL},
    {"BUILD", "Raise", POCKET_KINGDOM_MANAGER_ROWS_2, 30, {3, -8, -6, 0, 1, 1, 1, -3}, 5, 2, 4UL},
    {"LAW", "Decree", POCKET_KINGDOM_MANAGER_ROWS_3, 12, {-1, 4, 0, 0, 1, -2, 1, -1}, 4, 3, 8UL},
    {"COURT", "Listen", POCKET_KINGDOM_MANAGER_ROWS_4, 10, {1, 0, 0, 1, 0, 2, 1, -2}, 3, 4, 16UL},
    {"EVENT", "Answer", POCKET_KINGDOM_MANAGER_ROWS_5, 36, {-4, -4, -2, -1, 1, -3, 0, 4}, 5, 5, 32UL},
    {"YEAR", "Report", POCKET_KINGDOM_MANAGER_ROWS_6, 8, {2, 2, 1, 1, 1, 2, 1, -2}, 5, 6, 64UL},
};

static const CardputerGameCore::NamedValue EVENTS[] = {
    {"Pressure 01", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Choice 02", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Discovery 03", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Trouble 04", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Favor 05", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Warning 06", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Breakthrough 07", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Setback 08", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Pressure 09", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Choice 10", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Discovery 11", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Trouble 12", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Favor 13", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Warning 14", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Breakthrough 15", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Setback 16", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Pressure 17", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Choice 18", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Discovery 19", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Trouble 20", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Favor 21", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Warning 22", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Breakthrough 23", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Setback 24", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Pressure 25", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Choice 26", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Discovery 27", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Trouble 28", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Favor 29", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Warning 30", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Breakthrough 31", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Setback 32", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Pressure 33", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Choice 34", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Discovery 35", "A bespoke Pocket Kingdom event changes saved state and story flags."},
    {"Trouble 36", "A bespoke Pocket Kingdom event changes saved state and story flags."},
};

static const CardputerGameCore::NamedValue ENDINGS[] = {
    {"Golden Age", "Ending path 1: resources, flags, and reputation decide this outcome."},
    {"Iron Crown", "Ending path 2: resources, flags, and reputation decide this outcome."},
    {"Holy Mandate", "Ending path 3: resources, flags, and reputation decide this outcome."},
    {"Wizard Pact", "Ending path 4: resources, flags, and reputation decide this outcome."},
    {"People Rule", "Ending path 5: resources, flags, and reputation decide this outcome."},
    {"Dragon Treaty", "Ending path 6: resources, flags, and reputation decide this outcome."},
    {"Broken Realm", "Ending path 7: resources, flags, and reputation decide this outcome."},
};

static const CardputerGameCore::DeepGameDefinition DEF = {
    "Pocket Kingdom",
    "pocket-kingdom-manager",
    "Seasonal kingdom ledger",
    "PKM2",
    RESOURCES,
    sizeof(RESOURCES) / sizeof(RESOURCES[0]),
    SCREENS,
    sizeof(SCREENS) / sizeof(SCREENS[0]),
    EVENTS,
    sizeof(EVENTS) / sizeof(EVENTS[0]),
    ENDINGS,
    sizeof(ENDINGS) / sizeof(ENDINGS[0]),
    180,
    0xFFE0,
    0xFD20
};

const CardputerGameCore::DeepGameDefinition& gameDefinition() {
  return DEF;
}
