#include "GameData.h"

static const CardputerGameCore::ResourceDef RESOURCES[] = {
    {"Cred", 35, 0, 999, 6, -3},
    {"Batt", 85, 0, 100, -5, 10},
    {"Heat", 5, 0, 100, 5, -7},
    {"Deck", 90, 0, 100, -4, 6},
    {"Rep", 10, 0, 99, 2, 0},
    {"Files", 0, 0, 99, 2, 0},
    {"Trace", 0, 0, 100, 4, -5},
    {"Ghost", 0, 0, 99, 1, 0},
};

static const CardputerGameCore::NamedValue CYBERDECK_HACKER_RPG_ROWS_0[] = {
    {"Client 01", "Rest client #1: sets job board context"},
    {"Rumor 02", "Rest rumor #2: sets job board context"},
    {"Cache 03", "Rest cache #3: sets job board context"},
    {"Debt 04", "Rest debt #4: sets job board context"},
    {"Fence 05", "Rest fence #5: sets job board context"},
    {"Patch 06", "Rest patch #6: sets job board context"},
    {"Client 07", "Rest client #7: sets job board context"},
    {"Rumor 08", "Rest rumor #8: sets job board context"},
    {"Cache 09", "Rest cache #9: sets job board context"},
    {"Debt 10", "Rest debt #10: sets job board context"},
    {"Fence 11", "Rest fence #11: sets job board context"},
    {"Patch 12", "Rest patch #12: sets job board context"},
};

static const CardputerGameCore::NamedValue CYBERDECK_HACKER_RPG_ROWS_1[] = {
    {"Glass Bank Sim 01", "Take glass bank sim #1: loads a fictional target"},
    {"Transit Ghostbox 02", "Take transit ghostbox #2: loads a fictional target"},
    {"Clinic Mirror 03", "Take clinic mirror #3: loads a fictional target"},
    {"Weather Feed 04", "Take weather feed #4: loads a fictional target"},
    {"Servo Pawn 05", "Take servo pawn #5: loads a fictional target"},
    {"Underpass 06", "Take underpass #6: loads a fictional target"},
    {"Root Door 07", "Take root door #7: loads a fictional target"},
    {"Ledger Sim 08", "Take ledger sim #8: loads a fictional target"},
    {"Glass Bank Sim 09", "Take glass bank sim #9: loads a fictional target"},
    {"Transit Ghostbox 10", "Take transit ghostbox #10: loads a fictional target"},
    {"Clinic Mirror 11", "Take clinic mirror #11: loads a fictional target"},
    {"Weather Feed 12", "Take weather feed #12: loads a fictional target"},
    {"Servo Pawn 13", "Take servo pawn #13: loads a fictional target"},
    {"Underpass 14", "Take underpass #14: loads a fictional target"},
    {"Root Door 15", "Take root door #15: loads a fictional target"},
    {"Ledger Sim 16", "Take ledger sim #16: loads a fictional target"},
    {"Glass Bank Sim 17", "Take glass bank sim #17: loads a fictional target"},
    {"Transit Ghostbox 18", "Take transit ghostbox #18: loads a fictional target"},
    {"Clinic Mirror 19", "Take clinic mirror #19: loads a fictional target"},
    {"Weather Feed 20", "Take weather feed #20: loads a fictional target"},
    {"Servo Pawn 21", "Take servo pawn #21: loads a fictional target"},
    {"Underpass 22", "Take underpass #22: loads a fictional target"},
    {"Root Door 23", "Take root door #23: loads a fictional target"},
    {"Ledger Sim 24", "Take ledger sim #24: loads a fictional target"},
    {"Glass Bank Sim 25", "Take glass bank sim #25: loads a fictional target"},
    {"Transit Ghostbox 26", "Take transit ghostbox #26: loads a fictional target"},
    {"Clinic Mirror 27", "Take clinic mirror #27: loads a fictional target"},
    {"Weather Feed 28", "Take weather feed #28: loads a fictional target"},
    {"Servo Pawn 29", "Take servo pawn #29: loads a fictional target"},
    {"Underpass 30", "Take underpass #30: loads a fictional target"},
    {"Root Door 31", "Take root door #31: loads a fictional target"},
    {"Ledger Sim 32", "Take ledger sim #32: loads a fictional target"},
};

static const CardputerGameCore::NamedValue CYBERDECK_HACKER_RPG_ROWS_2[] = {
    {"Scan 01", "Run scan #1: changes fake node meters only"},
    {"Spoof 02", "Run spoof #2: changes fake node meters only"},
    {"Decrypt 03", "Run decrypt #3: changes fake node meters only"},
    {"Inject 04", "Run inject #4: changes fake node meters only"},
    {"Scrub 05", "Run scrub #5: changes fake node meters only"},
    {"Disconnect 06", "Run disconnect #6: changes fake node meters only"},
    {"Trace Map 07", "Run trace map #7: changes fake node meters only"},
    {"Ghost Fork 08", "Run ghost fork #8: changes fake node meters only"},
    {"Scan 09", "Run scan #9: changes fake node meters only"},
    {"Spoof 10", "Run spoof #10: changes fake node meters only"},
    {"Decrypt 11", "Run decrypt #11: changes fake node meters only"},
    {"Inject 12", "Run inject #12: changes fake node meters only"},
    {"Scrub 13", "Run scrub #13: changes fake node meters only"},
    {"Disconnect 14", "Run disconnect #14: changes fake node meters only"},
    {"Trace Map 15", "Run trace map #15: changes fake node meters only"},
    {"Ghost Fork 16", "Run ghost fork #16: changes fake node meters only"},
    {"Scan 17", "Run scan #17: changes fake node meters only"},
    {"Spoof 18", "Run spoof #18: changes fake node meters only"},
    {"Decrypt 19", "Run decrypt #19: changes fake node meters only"},
    {"Inject 20", "Run inject #20: changes fake node meters only"},
};

static const CardputerGameCore::NamedValue CYBERDECK_HACKER_RPG_ROWS_3[] = {
    {"Scanner 01", "Upgrade scanner #1: reduces fake-job risk"},
    {"Decryptor 02", "Upgrade decryptor #2: reduces fake-job risk"},
    {"Spoof Chip 03", "Upgrade spoof chip #3: reduces fake-job risk"},
    {"Injector 04", "Upgrade injector #4: reduces fake-job risk"},
    {"Trace Map 05", "Upgrade trace map #5: reduces fake-job risk"},
    {"Blackbox 06", "Upgrade blackbox #6: reduces fake-job risk"},
    {"Battery 07", "Upgrade battery #7: reduces fake-job risk"},
    {"Shield 08", "Upgrade shield #8: reduces fake-job risk"},
};

static const CardputerGameCore::NamedValue CYBERDECK_HACKER_RPG_ROWS_4[] = {
    {"Ledger 01", "Read ledger #1: advances story flags"},
    {"Clinic 02", "Read clinic #2: advances story flags"},
    {"Weather 03", "Read weather #3: advances story flags"},
    {"Transit 04", "Read transit #4: advances story flags"},
    {"Ghost 05", "Read ghost #5: advances story flags"},
    {"Civic 06", "Read civic #6: advances story flags"},
    {"Street 07", "Read street #7: advances story flags"},
    {"Crown 08", "Read crown #8: advances story flags"},
    {"Ledger 09", "Read ledger #9: advances story flags"},
    {"Clinic 10", "Read clinic #10: advances story flags"},
    {"Weather 11", "Read weather #11: advances story flags"},
    {"Transit 12", "Read transit #12: advances story flags"},
    {"Ghost 13", "Read ghost #13: advances story flags"},
    {"Civic 14", "Read civic #14: advances story flags"},
    {"Street 15", "Read street #15: advances story flags"},
    {"Crown 16", "Read crown #16: advances story flags"},
    {"Ledger 17", "Read ledger #17: advances story flags"},
    {"Clinic 18", "Read clinic #18: advances story flags"},
    {"Weather 19", "Read weather #19: advances story flags"},
    {"Transit 20", "Read transit #20: advances story flags"},
    {"Ghost 21", "Read ghost #21: advances story flags"},
    {"Civic 22", "Read civic #22: advances story flags"},
    {"Street 23", "Read street #23: advances story flags"},
    {"Crown 24", "Read crown #24: advances story flags"},
};

static const CardputerGameCore::NamedValue CYBERDECK_HACKER_RPG_ROWS_5[] = {
    {"Cold CPU 01", "Buy cold cpu #1: spends credits for deck edge"},
    {"Battery Stack 02", "Buy battery stack #2: spends credits for deck edge"},
    {"Clean Shell 03", "Buy clean shell #3: spends credits for deck edge"},
    {"Spoof Key 04", "Buy spoof key #4: spends credits for deck edge"},
    {"Trace Sink 05", "Buy trace sink #5: spends credits for deck edge"},
    {"Patch Kit 06", "Buy patch kit #6: spends credits for deck edge"},
    {"Cold CPU 07", "Buy cold cpu #7: spends credits for deck edge"},
    {"Battery Stack 08", "Buy battery stack #8: spends credits for deck edge"},
    {"Clean Shell 09", "Buy clean shell #9: spends credits for deck edge"},
    {"Spoof Key 10", "Buy spoof key #10: spends credits for deck edge"},
    {"Trace Sink 11", "Buy trace sink #11: spends credits for deck edge"},
    {"Patch Kit 12", "Buy patch kit #12: spends credits for deck edge"},
};

static const CardputerGameCore::NamedValue CYBERDECK_HACKER_RPG_ROWS_6[] = {
    {"Street 01", "Choose street #1: forks ending pressure"},
    {"Corp 02", "Choose corp #2: forks ending pressure"},
    {"Signal 03", "Choose signal #3: forks ending pressure"},
    {"Civic 04", "Choose civic #4: forks ending pressure"},
    {"Street 05", "Choose street #5: forks ending pressure"},
    {"Corp 06", "Choose corp #6: forks ending pressure"},
    {"Signal 07", "Choose signal #7: forks ending pressure"},
    {"Civic 08", "Choose civic #8: forks ending pressure"},
    {"Street 09", "Choose street #9: forks ending pressure"},
    {"Corp 10", "Choose corp #10: forks ending pressure"},
    {"Signal 11", "Choose signal #11: forks ending pressure"},
    {"Civic 12", "Choose civic #12: forks ending pressure"},
};

static const CardputerGameCore::DeepScreenDef SCREENS[] = {
    {"SAFEHOUSE", "Rest", CYBERDECK_HACKER_RPG_ROWS_0, 12, {1, 6, -5, 4, 1, 0, -4, 0}, 3, 0, 1UL},
    {"JOB BOARD", "Take", CYBERDECK_HACKER_RPG_ROWS_1, 32, {8, -2, 4, -2, 1, 1, 3, 1}, 5, 1, 2UL},
    {"NODE", "Run", CYBERDECK_HACKER_RPG_ROWS_2, 20, {4, -5, 5, -4, 1, 2, 5, 1}, 5, 2, 4UL},
    {"TOOLS", "Upgrade", CYBERDECK_HACKER_RPG_ROWS_3, 8, {-8, 2, -1, 3, 1, 1, -2, 0}, 4, 3, 8UL},
    {"FILES", "Read", CYBERDECK_HACKER_RPG_ROWS_4, 24, {1, 0, 1, 0, 1, 3, 0, 2}, 3, 4, 16UL},
    {"MARKET", "Buy", CYBERDECK_HACKER_RPG_ROWS_5, 12, {-10, 4, -2, 5, 1, 0, -4, 0}, 4, 5, 32UL},
    {"REP", "Choose", CYBERDECK_HACKER_RPG_ROWS_6, 12, {2, 0, 2, 0, 3, 1, 1, 1}, 3, 6, 64UL},
};

static const CardputerGameCore::NamedValue EVENTS[] = {
    {"Pressure 01", "A bespoke Cyberdeck RPG event changes saved state and story flags."},
    {"Choice 02", "A bespoke Cyberdeck RPG event changes saved state and story flags."},
    {"Discovery 03", "A bespoke Cyberdeck RPG event changes saved state and story flags."},
    {"Trouble 04", "A bespoke Cyberdeck RPG event changes saved state and story flags."},
    {"Favor 05", "A bespoke Cyberdeck RPG event changes saved state and story flags."},
    {"Warning 06", "A bespoke Cyberdeck RPG event changes saved state and story flags."},
    {"Breakthrough 07", "A bespoke Cyberdeck RPG event changes saved state and story flags."},
    {"Setback 08", "A bespoke Cyberdeck RPG event changes saved state and story flags."},
    {"Pressure 09", "A bespoke Cyberdeck RPG event changes saved state and story flags."},
    {"Choice 10", "A bespoke Cyberdeck RPG event changes saved state and story flags."},
    {"Discovery 11", "A bespoke Cyberdeck RPG event changes saved state and story flags."},
    {"Trouble 12", "A bespoke Cyberdeck RPG event changes saved state and story flags."},
    {"Favor 13", "A bespoke Cyberdeck RPG event changes saved state and story flags."},
    {"Warning 14", "A bespoke Cyberdeck RPG event changes saved state and story flags."},
    {"Breakthrough 15", "A bespoke Cyberdeck RPG event changes saved state and story flags."},
    {"Setback 16", "A bespoke Cyberdeck RPG event changes saved state and story flags."},
    {"Pressure 17", "A bespoke Cyberdeck RPG event changes saved state and story flags."},
    {"Choice 18", "A bespoke Cyberdeck RPG event changes saved state and story flags."},
    {"Discovery 19", "A bespoke Cyberdeck RPG event changes saved state and story flags."},
    {"Trouble 20", "A bespoke Cyberdeck RPG event changes saved state and story flags."},
    {"Favor 21", "A bespoke Cyberdeck RPG event changes saved state and story flags."},
    {"Warning 22", "A bespoke Cyberdeck RPG event changes saved state and story flags."},
    {"Breakthrough 23", "A bespoke Cyberdeck RPG event changes saved state and story flags."},
    {"Setback 24", "A bespoke Cyberdeck RPG event changes saved state and story flags."},
    {"Pressure 25", "A bespoke Cyberdeck RPG event changes saved state and story flags."},
    {"Choice 26", "A bespoke Cyberdeck RPG event changes saved state and story flags."},
    {"Discovery 27", "A bespoke Cyberdeck RPG event changes saved state and story flags."},
    {"Trouble 28", "A bespoke Cyberdeck RPG event changes saved state and story flags."},
    {"Favor 29", "A bespoke Cyberdeck RPG event changes saved state and story flags."},
    {"Warning 30", "A bespoke Cyberdeck RPG event changes saved state and story flags."},
    {"Breakthrough 31", "A bespoke Cyberdeck RPG event changes saved state and story flags."},
    {"Setback 32", "A bespoke Cyberdeck RPG event changes saved state and story flags."},
};

static const CardputerGameCore::NamedValue ENDINGS[] = {
    {"Clean Root", "Ending path 1: resources, flags, and reputation decide this outcome."},
    {"Rich Burnout", "Ending path 2: resources, flags, and reputation decide this outcome."},
    {"Street Myth", "Ending path 3: resources, flags, and reputation decide this outcome."},
    {"Ghost File", "Ending path 4: resources, flags, and reputation decide this outcome."},
    {"Corp Deal", "Ending path 5: resources, flags, and reputation decide this outcome."},
    {"Deck Dead", "Ending path 6: resources, flags, and reputation decide this outcome."},
};

static const CardputerGameCore::DeepGameDefinition DEF = {
    "Cyberdeck RPG",
    "cyberdeck-hacker-rpg",
    "Offline fake node crawl",
    "CDR2",
    RESOURCES,
    sizeof(RESOURCES) / sizeof(RESOURCES[0]),
    SCREENS,
    sizeof(SCREENS) / sizeof(SCREENS[0]),
    EVENTS,
    sizeof(EVENTS) / sizeof(EVENTS[0]),
    ENDINGS,
    sizeof(ENDINGS) / sizeof(ENDINGS[0]),
    170,
    0x07FF,
    0xFD20
};

const CardputerGameCore::DeepGameDefinition& gameDefinition() {
  return DEF;
}
