#include "GameData.h"

static const CardputerGameCore::ResourceDef RESOURCES[] = {
    {"Funds", 35, 0, 999, 4, -2},
    {"Stam", 80, 0, 100, -5, 8},
    {"Batt", 85, 0, 100, -6, 10},
    {"Heat", 5, 0, 100, 4, -5},
    {"Clues", 0, 0, 99, 2, 0},
    {"Trust", 35, 0, 100, 1, 2},
};

static const CardputerGameCore::NamedValue CYBER_RANGER_ROWS_0[] = {
    {"Pine 01", "Plan pine #1: sets active case"},
    {"Lake 02", "Plan lake #2: sets active case"},
    {"Ridge 03", "Plan ridge #3: sets active case"},
    {"Bog 04", "Plan bog #4: sets active case"},
    {"Lodge 05", "Plan lodge #5: sets active case"},
    {"Road 06", "Plan road #6: sets active case"},
    {"Cave 07", "Plan cave #7: sets active case"},
    {"Meadow 08", "Plan meadow #8: sets active case"},
};

static const CardputerGameCore::NamedValue CYBER_RANGER_ROWS_1[] = {
    {"Pine 01", "Patrol pine #1: finds field evidence"},
    {"Lake 02", "Patrol lake #2: finds field evidence"},
    {"Ridge 03", "Patrol ridge #3: finds field evidence"},
    {"Bog 04", "Patrol bog #4: finds field evidence"},
    {"Lodge 05", "Patrol lodge #5: finds field evidence"},
    {"Road 06", "Patrol road #6: finds field evidence"},
    {"Cave 07", "Patrol cave #7: finds field evidence"},
    {"Meadow 08", "Patrol meadow #8: finds field evidence"},
};

static const CardputerGameCore::NamedValue CYBER_RANGER_ROWS_2[] = {
    {"Weather Echo 01", "Inspect weather echo #1: fictional table pings only"},
    {"Tag Glitch 02", "Inspect tag glitch #2: fictional table pings only"},
    {"Sensor Ghost 03", "Inspect sensor ghost #3: fictional table pings only"},
    {"Bio Trace 04", "Inspect bio trace #4: fictional table pings only"},
    {"Weather Echo 05", "Inspect weather echo #5: fictional table pings only"},
    {"Tag Glitch 06", "Inspect tag glitch #6: fictional table pings only"},
    {"Sensor Ghost 07", "Inspect sensor ghost #7: fictional table pings only"},
    {"Bio Trace 08", "Inspect bio trace #8: fictional table pings only"},
    {"Weather Echo 09", "Inspect weather echo #9: fictional table pings only"},
    {"Tag Glitch 10", "Inspect tag glitch #10: fictional table pings only"},
    {"Sensor Ghost 11", "Inspect sensor ghost #11: fictional table pings only"},
    {"Bio Trace 12", "Inspect bio trace #12: fictional table pings only"},
    {"Weather Echo 13", "Inspect weather echo #13: fictional table pings only"},
    {"Tag Glitch 14", "Inspect tag glitch #14: fictional table pings only"},
    {"Sensor Ghost 15", "Inspect sensor ghost #15: fictional table pings only"},
    {"Bio Trace 16", "Inspect bio trace #16: fictional table pings only"},
    {"Weather Echo 17", "Inspect weather echo #17: fictional table pings only"},
    {"Tag Glitch 18", "Inspect tag glitch #18: fictional table pings only"},
    {"Sensor Ghost 19", "Inspect sensor ghost #19: fictional table pings only"},
    {"Bio Trace 20", "Inspect bio trace #20: fictional table pings only"},
    {"Weather Echo 21", "Inspect weather echo #21: fictional table pings only"},
    {"Tag Glitch 22", "Inspect tag glitch #22: fictional table pings only"},
    {"Sensor Ghost 23", "Inspect sensor ghost #23: fictional table pings only"},
    {"Bio Trace 24", "Inspect bio trace #24: fictional table pings only"},
    {"Weather Echo 25", "Inspect weather echo #25: fictional table pings only"},
    {"Tag Glitch 26", "Inspect tag glitch #26: fictional table pings only"},
    {"Sensor Ghost 27", "Inspect sensor ghost #27: fictional table pings only"},
    {"Bio Trace 28", "Inspect bio trace #28: fictional table pings only"},
    {"Weather Echo 29", "Inspect weather echo #29: fictional table pings only"},
    {"Tag Glitch 30", "Inspect tag glitch #30: fictional table pings only"},
    {"Sensor Ghost 31", "Inspect sensor ghost #31: fictional table pings only"},
    {"Bio Trace 32", "Inspect bio trace #32: fictional table pings only"},
};

static const CardputerGameCore::NamedValue CYBER_RANGER_ROWS_3[] = {
    {"Scan 01", "Run scan #1: uses fake deck math only"},
    {"Map 02", "Run map #2: uses fake deck math only"},
    {"Tag 03", "Run tag #3: uses fake deck math only"},
    {"Decode 04", "Run decode #4: uses fake deck math only"},
    {"Log 05", "Run log #5: uses fake deck math only"},
    {"Shield 06", "Run shield #6: uses fake deck math only"},
    {"Savebat 07", "Run savebat #7: uses fake deck math only"},
    {"Compass 08", "Run compass #8: uses fake deck math only"},
};

static const CardputerGameCore::NamedValue CYBER_RANGER_ROWS_4[] = {
    {"Pinewake 01", "Study pinewake #1: reveals guide states"},
    {"Lakewire 02", "Study lakewire #2: reveals guide states"},
    {"Ridgecat 03", "Study ridgecat #3: reveals guide states"},
    {"Bogleaf 04", "Study bogleaf #4: reveals guide states"},
    {"Lodge Moth 05", "Study lodge moth #5: reveals guide states"},
    {"Road Deer 06", "Study road deer #6: reveals guide states"},
    {"Cave Echo 07", "Study cave echo #7: reveals guide states"},
    {"Meadow Crown 08", "Study meadow crown #8: reveals guide states"},
    {"Pinewake 09", "Study pinewake #9: reveals guide states"},
    {"Lakewire 10", "Study lakewire #10: reveals guide states"},
    {"Ridgecat 11", "Study ridgecat #11: reveals guide states"},
    {"Bogleaf 12", "Study bogleaf #12: reveals guide states"},
    {"Lodge Moth 13", "Study lodge moth #13: reveals guide states"},
    {"Road Deer 14", "Study road deer #14: reveals guide states"},
    {"Cave Echo 15", "Study cave echo #15: reveals guide states"},
    {"Meadow Crown 16", "Study meadow crown #16: reveals guide states"},
    {"Pinewake 17", "Study pinewake #17: reveals guide states"},
    {"Lakewire 18", "Study lakewire #18: reveals guide states"},
    {"Ridgecat 19", "Study ridgecat #19: reveals guide states"},
    {"Bogleaf 20", "Study bogleaf #20: reveals guide states"},
};

static const CardputerGameCore::NamedValue CYBER_RANGER_ROWS_5[] = {
    {"Pine Sensor 01", "Resolve pine sensor #1: needs bio and signal evidence"},
    {"Lake Tag 02", "Resolve lake tag #2: needs bio and signal evidence"},
    {"Ridge Relay 03", "Resolve ridge relay #3: needs bio and signal evidence"},
    {"Bog Echo 04", "Resolve bog echo #4: needs bio and signal evidence"},
    {"Old Lodge 05", "Resolve old lodge #5: needs bio and signal evidence"},
    {"Fire Road 06", "Resolve fire road #6: needs bio and signal evidence"},
    {"Cave Line 07", "Resolve cave line #7: needs bio and signal evidence"},
    {"Drone Meadow 08", "Resolve drone meadow #8: needs bio and signal evidence"},
};

static const CardputerGameCore::NamedValue CYBER_RANGER_ROWS_6[] = {
    {"Scanner 01", "Upgrade scanner #1: reduces battery or heat"},
    {"Mapper 02", "Upgrade mapper #2: reduces battery or heat"},
    {"Decoder 03", "Upgrade decoder #3: reduces battery or heat"},
    {"Tag Reader 04", "Upgrade tag reader #4: reduces battery or heat"},
    {"Log Tool 05", "Upgrade log tool #5: reduces battery or heat"},
    {"Shield 06", "Upgrade shield #6: reduces battery or heat"},
    {"Saver 07", "Upgrade saver #7: reduces battery or heat"},
    {"Compass 08", "Upgrade compass #8: reduces battery or heat"},
};

static const CardputerGameCore::DeepScreenDef SCREENS[] = {
    {"STATION", "Plan", CYBER_RANGER_ROWS_0, 8, {2, 3, 2, -2, 1, 2, 0, 0}, 3, 0, 1UL},
    {"PARK", "Patrol", CYBER_RANGER_ROWS_1, 8, {2, -5, -4, 2, 2, 1, 0, 0}, 5, 1, 2UL},
    {"SIGNAL", "Inspect", CYBER_RANGER_ROWS_2, 32, {2, -2, -5, 4, 3, 1, 0, 0}, 5, 2, 4UL},
    {"DECK", "Run", CYBER_RANGER_ROWS_3, 8, {1, -1, -5, 3, 2, 1, 0, 0}, 4, 3, 8UL},
    {"GUIDE", "Study", CYBER_RANGER_ROWS_4, 20, {0, 0, 0, -1, 2, 1, 0, 0}, 3, 4, 16UL},
    {"CASE", "Resolve", CYBER_RANGER_ROWS_5, 8, {5, -2, -2, 2, 4, 2, 0, 0}, 6, 5, 32UL},
    {"GEAR", "Upgrade", CYBER_RANGER_ROWS_6, 8, {-8, 0, 4, -2, 1, 2, 0, 0}, 4, 6, 64UL},
};

static const CardputerGameCore::NamedValue EVENTS[] = {
    {"Pressure 01", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Choice 02", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Discovery 03", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Trouble 04", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Favor 05", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Warning 06", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Breakthrough 07", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Setback 08", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Pressure 09", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Choice 10", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Discovery 11", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Trouble 12", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Favor 13", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Warning 14", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Breakthrough 15", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Setback 16", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Pressure 17", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Choice 18", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Discovery 19", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Trouble 20", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Favor 21", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Warning 22", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Breakthrough 23", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Setback 24", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Pressure 25", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Choice 26", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Discovery 27", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Trouble 28", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Favor 29", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Warning 30", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Breakthrough 31", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Setback 32", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Pressure 33", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Choice 34", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Discovery 35", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Trouble 36", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Favor 37", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Warning 38", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Breakthrough 39", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Setback 40", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Pressure 41", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Choice 42", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Discovery 43", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Trouble 44", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Favor 45", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Warning 46", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Breakthrough 47", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Setback 48", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Pressure 49", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Choice 50", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Discovery 51", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Trouble 52", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Favor 53", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Warning 54", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Breakthrough 55", "A bespoke Cyber Ranger event changes saved state and story flags."},
    {"Setback 56", "A bespoke Cyber Ranger event changes saved state and story flags."},
};

static const CardputerGameCore::NamedValue ENDINGS[] = {
    {"Park Truth", "Ending path 1: resources, flags, and reputation decide this outcome."},
    {"Science Archive", "Ending path 2: resources, flags, and reputation decide this outcome."},
    {"Town Cover", "Ending path 3: resources, flags, and reputation decide this outcome."},
    {"Corp Leak", "Ending path 4: resources, flags, and reputation decide this outcome."},
    {"Signal Pact", "Ending path 5: resources, flags, and reputation decide this outcome."},
    {"Burned Deck", "Ending path 6: resources, flags, and reputation decide this outcome."},
};

static const CardputerGameCore::DeepGameDefinition DEF = {
    "Cyber Ranger",
    "cyber-ranger",
    "Fictional cyber-wilderness",
    "CYR2",
    RESOURCES,
    sizeof(RESOURCES) / sizeof(RESOURCES[0]),
    SCREENS,
    sizeof(SCREENS) / sizeof(SCREENS[0]),
    EVENTS,
    sizeof(EVENTS) / sizeof(EVENTS[0]),
    ENDINGS,
    sizeof(ENDINGS) / sizeof(ENDINGS[0]),
    175,
    0x07BF,
    0xFD20
};

const CardputerGameCore::DeepGameDefinition& gameDefinition() {
  return DEF;
}
