#include "GameData.h"

static const CardputerGameCore::ResourceDef RESOURCES[] = {
    {"Pay", 30, 0, 999, 2, -1},
    {"Power", 80, 0, 100, -6, 10},
    {"Calm", 70, 0, 100, -4, 7},
    {"Trust", 30, 0, 100, 2, 1},
    {"Static", 10, 0, 100, 5, -6},
    {"Clues", 0, 0, 99, 2, 0},
    {"Entity", 0, 0, 100, 3, -2},
    {"Station", 90, 0, 100, -2, 3},
};

static const CardputerGameCore::NamedValue HAUNTED_RADIO_OPERATOR_ROWS_0[] = {
    {"Dawn 01", "Begin dawn #1: sets the night pressure"},
    {"Fog 02", "Begin fog #2: sets the night pressure"},
    {"Storm 03", "Begin storm #3: sets the night pressure"},
    {"Cold 04", "Begin cold #4: sets the night pressure"},
    {"Tape 05", "Begin tape #5: sets the night pressure"},
    {"Tower 06", "Begin tower #6: sets the night pressure"},
    {"Dawn 07", "Begin dawn #7: sets the night pressure"},
    {"Fog 08", "Begin fog #8: sets the night pressure"},
    {"Storm 09", "Begin storm #9: sets the night pressure"},
    {"Cold 10", "Begin cold #10: sets the night pressure"},
    {"Tape 11", "Begin tape #11: sets the night pressure"},
    {"Tower 12", "Begin tower #12: sets the night pressure"},
};

static const CardputerGameCore::NamedValue HAUNTED_RADIO_OPERATOR_ROWS_1[] = {
    {"Low Band 01", "Tune low band #1: uses fictional frequency keys only"},
    {"Ridge 02", "Tune ridge #2: uses fictional frequency keys only"},
    {"Lake 03", "Tune lake #3: uses fictional frequency keys only"},
    {"Numbers 04", "Tune numbers #4: uses fictional frequency keys only"},
    {"Dawn 05", "Tune dawn #5: uses fictional frequency keys only"},
};

static const CardputerGameCore::NamedValue HAUNTED_RADIO_OPERATOR_ROWS_2[] = {
    {"Caller 01", "Answer caller #1: updates case flags"},
    {"Mimic 02", "Answer mimic #2: updates case flags"},
    {"Number 03", "Answer number #3: updates case flags"},
    {"Weather 04", "Answer weather #4: updates case flags"},
    {"Hidden 05", "Answer hidden #5: updates case flags"},
    {"Ranger 06", "Answer ranger #6: updates case flags"},
    {"Child 07", "Answer child #7: updates case flags"},
    {"Archivist 08", "Answer archivist #8: updates case flags"},
    {"Caller 09", "Answer caller #9: updates case flags"},
    {"Mimic 10", "Answer mimic #10: updates case flags"},
    {"Number 11", "Answer number #11: updates case flags"},
    {"Weather 12", "Answer weather #12: updates case flags"},
    {"Hidden 13", "Answer hidden #13: updates case flags"},
    {"Ranger 14", "Answer ranger #14: updates case flags"},
    {"Child 15", "Answer child #15: updates case flags"},
    {"Archivist 16", "Answer archivist #16: updates case flags"},
    {"Caller 17", "Answer caller #17: updates case flags"},
    {"Mimic 18", "Answer mimic #18: updates case flags"},
    {"Number 19", "Answer number #19: updates case flags"},
    {"Weather 20", "Answer weather #20: updates case flags"},
    {"Hidden 21", "Answer hidden #21: updates case flags"},
    {"Ranger 22", "Answer ranger #22: updates case flags"},
    {"Child 23", "Answer child #23: updates case flags"},
    {"Archivist 24", "Answer archivist #24: updates case flags"},
    {"Caller 25", "Answer caller #25: updates case flags"},
    {"Mimic 26", "Answer mimic #26: updates case flags"},
    {"Number 27", "Answer number #27: updates case flags"},
    {"Weather 28", "Answer weather #28: updates case flags"},
    {"Hidden 29", "Answer hidden #29: updates case flags"},
    {"Ranger 30", "Answer ranger #30: updates case flags"},
    {"Child 31", "Answer child #31: updates case flags"},
    {"Archivist 32", "Answer archivist #32: updates case flags"},
    {"Caller 33", "Answer caller #33: updates case flags"},
    {"Mimic 34", "Answer mimic #34: updates case flags"},
    {"Number 35", "Answer number #35: updates case flags"},
    {"Weather 36", "Answer weather #36: updates case flags"},
    {"Hidden 37", "Answer hidden #37: updates case flags"},
    {"Ranger 38", "Answer ranger #38: updates case flags"},
    {"Child 39", "Answer child #39: updates case flags"},
    {"Archivist 40", "Answer archivist #40: updates case flags"},
};

static const CardputerGameCore::NamedValue HAUNTED_RADIO_OPERATOR_ROWS_3[] = {
    {"Callsign 01", "Decode callsign #1: spends power to reveal clues"},
    {"Reverse 02", "Decode reverse #2: spends power to reveal clues"},
    {"Grid 03", "Decode grid #3: spends power to reveal clues"},
    {"Tapcode 04", "Decode tapcode #4: spends power to reveal clues"},
    {"Weather Log 05", "Decode weather log #5: spends power to reveal clues"},
    {"Replay 06", "Decode replay #6: spends power to reveal clues"},
};

static const CardputerGameCore::NamedValue HAUNTED_RADIO_OPERATOR_ROWS_4[] = {
    {"Hiker 01", "Review hiker #1: checks mystery progress"},
    {"Mill 02", "Review mill #2: checks mystery progress"},
    {"Camp 9 03", "Review camp 9 #3: checks mystery progress"},
    {"Lake Voice 04", "Review lake voice #4: checks mystery progress"},
    {"Tunnel 05", "Review tunnel #5: checks mystery progress"},
    {"Numbers 06", "Review numbers #6: checks mystery progress"},
    {"Black Pine 07", "Review black pine #7: checks mystery progress"},
    {"Dawn Band 08", "Review dawn band #8: checks mystery progress"},
};

static const CardputerGameCore::NamedValue HAUNTED_RADIO_OPERATOR_ROWS_5[] = {
    {"Callsign 01", "Read callsign #1: surfaces discovered snippets"},
    {"Tape 02", "Read tape #2: surfaces discovered snippets"},
    {"Map 03", "Read map #3: surfaces discovered snippets"},
    {"Contradiction 04", "Read contradiction #4: surfaces discovered snippets"},
    {"Tell 05", "Read tell #5: surfaces discovered snippets"},
    {"Weather 06", "Read weather #6: surfaces discovered snippets"},
    {"Callsign 07", "Read callsign #7: surfaces discovered snippets"},
    {"Tape 08", "Read tape #8: surfaces discovered snippets"},
    {"Map 09", "Read map #9: surfaces discovered snippets"},
    {"Contradiction 10", "Read contradiction #10: surfaces discovered snippets"},
    {"Tell 11", "Read tell #11: surfaces discovered snippets"},
    {"Weather 12", "Read weather #12: surfaces discovered snippets"},
    {"Callsign 13", "Read callsign #13: surfaces discovered snippets"},
    {"Tape 14", "Read tape #14: surfaces discovered snippets"},
    {"Map 15", "Read map #15: surfaces discovered snippets"},
    {"Contradiction 16", "Read contradiction #16: surfaces discovered snippets"},
    {"Tell 17", "Read tell #17: surfaces discovered snippets"},
    {"Weather 18", "Read weather #18: surfaces discovered snippets"},
    {"Callsign 19", "Read callsign #19: surfaces discovered snippets"},
    {"Tape 20", "Read tape #20: surfaces discovered snippets"},
    {"Map 21", "Read map #21: surfaces discovered snippets"},
    {"Contradiction 22", "Read contradiction #22: surfaces discovered snippets"},
    {"Tell 23", "Read tell #23: surfaces discovered snippets"},
    {"Weather 24", "Read weather #24: surfaces discovered snippets"},
};

static const CardputerGameCore::NamedValue HAUNTED_RADIO_OPERATOR_ROWS_6[] = {
    {"Antenna 01", "Reroute antenna #1: trades power for safety"},
    {"Recorder 02", "Reroute recorder #2: trades power for safety"},
    {"Heater 03", "Reroute heater #3: trades power for safety"},
    {"Floodlight 04", "Reroute floodlight #4: trades power for safety"},
    {"Beacon 05", "Reroute beacon #5: trades power for safety"},
    {"Battery 06", "Reroute battery #6: trades power for safety"},
    {"Antenna 07", "Reroute antenna #7: trades power for safety"},
    {"Recorder 08", "Reroute recorder #8: trades power for safety"},
    {"Heater 09", "Reroute heater #9: trades power for safety"},
    {"Floodlight 10", "Reroute floodlight #10: trades power for safety"},
    {"Beacon 11", "Reroute beacon #11: trades power for safety"},
    {"Battery 12", "Reroute battery #12: trades power for safety"},
};

static const CardputerGameCore::DeepScreenDef SCREENS[] = {
    {"STATION", "Begin", HAUNTED_RADIO_OPERATOR_ROWS_0, 12, {1, -3, -2, 1, 3, 1, 2, -1}, 3, 0, 1UL},
    {"TUNE", "Tune", HAUNTED_RADIO_OPERATOR_ROWS_1, 5, {0, -4, -1, 1, 4, 2, 2, -1}, 4, 1, 2UL},
    {"SIGNAL", "Answer", HAUNTED_RADIO_OPERATOR_ROWS_2, 40, {1, -5, -3, 2, 5, 3, 3, -2}, 5, 2, 4UL},
    {"DECODE", "Decode", HAUNTED_RADIO_OPERATOR_ROWS_3, 6, {0, -4, -2, 1, -2, 4, 1, 0}, 5, 3, 8UL},
    {"CASES", "Review", HAUNTED_RADIO_OPERATOR_ROWS_4, 8, {0, 0, 1, 1, -1, 2, -1, 0}, 3, 4, 16UL},
    {"LOGS", "Read", HAUNTED_RADIO_OPERATOR_ROWS_5, 24, {0, 0, 2, 1, -1, 1, -1, 0}, 2, 5, 32UL},
    {"POWER", "Reroute", HAUNTED_RADIO_OPERATOR_ROWS_6, 12, {0, -3, 3, 0, -2, 1, -2, 3}, 3, 6, 64UL},
};

static const CardputerGameCore::NamedValue EVENTS[] = {
    {"Pressure 01", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Choice 02", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Discovery 03", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Trouble 04", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Favor 05", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Warning 06", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Breakthrough 07", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Setback 08", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Pressure 09", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Choice 10", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Discovery 11", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Trouble 12", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Favor 13", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Warning 14", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Breakthrough 15", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Setback 16", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Pressure 17", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Choice 18", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Discovery 19", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Trouble 20", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Favor 21", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Warning 22", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Breakthrough 23", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Setback 24", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Pressure 25", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Choice 26", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Discovery 27", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Trouble 28", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Favor 29", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Warning 30", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Breakthrough 31", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Setback 32", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Pressure 33", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Choice 34", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Discovery 35", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Trouble 36", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Favor 37", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Warning 38", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Breakthrough 39", "A bespoke Haunted Radio event changes saved state and story flags."},
    {"Setback 40", "A bespoke Haunted Radio event changes saved state and story flags."},
};

static const CardputerGameCore::NamedValue ENDINGS[] = {
    {"Dawn Operator", "Ending path 1: resources, flags, and reputation decide this outcome."},
    {"Vanished Shift", "Ending path 2: resources, flags, and reputation decide this outcome."},
    {"Truth Broadcast", "Ending path 3: resources, flags, and reputation decide this outcome."},
    {"Quiet Coverup", "Ending path 4: resources, flags, and reputation decide this outcome."},
    {"Signal Friend", "Ending path 5: resources, flags, and reputation decide this outcome."},
    {"Tower Dark", "Ending path 6: resources, flags, and reputation decide this outcome."},
};

static const CardputerGameCore::DeepGameDefinition DEF = {
    "Haunted Radio",
    "haunted-radio-operator",
    "Fictional station mystery",
    "HRO2",
    RESOURCES,
    sizeof(RESOURCES) / sizeof(RESOURCES[0]),
    SCREENS,
    sizeof(SCREENS) / sizeof(SCREENS[0]),
    EVENTS,
    sizeof(EVENTS) / sizeof(EVENTS[0]),
    ENDINGS,
    sizeof(ENDINGS) / sizeof(ENDINGS[0]),
    165,
    0xBDF7,
    0xFD20
};

const CardputerGameCore::DeepGameDefinition& gameDefinition() {
  return DEF;
}
