#include "GameData.h"

static const CardputerGameCore::ResourceDef RESOURCES[] = {
    {"Cash", 40, 0, 999, 3, -2},
    {"Time", 30, 0, 99, -2, 3},
    {"Rep", 25, 0, 100, 2, 0},
    {"Heat", 5, 0, 100, 3, -3},
    {"Clues", 0, 0, 99, 2, 0},
    {"Trust", 25, 0, 100, 1, 1},
};

static const CardputerGameCore::NamedValue POCKET_DETECTIVE_AGENCY_ROWS_0[] = {
    {"Glass Cat 01", "Open glass cat #1: starts or reviews a case"},
    {"Missing Key 02", "Open missing key #2: starts or reviews a case"},
    {"Red Receipt 03", "Open red receipt #3: starts or reviews a case"},
    {"Old Names 04", "Open old names #4: starts or reviews a case"},
};

static const CardputerGameCore::NamedValue POCKET_DETECTIVE_AGENCY_ROWS_1[] = {
    {"Client 01", "Study client #1: reveals required proof"},
    {"Clock 02", "Study clock #2: reveals required proof"},
    {"Suspect 03", "Study suspect #3: reveals required proof"},
    {"Motive 04", "Study motive #4: reveals required proof"},
    {"Reward 05", "Study reward #5: reveals required proof"},
    {"Risk 06", "Study risk #6: reveals required proof"},
    {"Client 07", "Study client #7: reveals required proof"},
    {"Clock 08", "Study clock #8: reveals required proof"},
    {"Suspect 09", "Study suspect #9: reveals required proof"},
    {"Motive 10", "Study motive #10: reveals required proof"},
    {"Reward 11", "Study reward #11: reveals required proof"},
    {"Risk 12", "Study risk #12: reveals required proof"},
};

static const CardputerGameCore::NamedValue POCKET_DETECTIVE_AGENCY_ROWS_2[] = {
    {"Diner 01", "Visit diner #1: finds location clues"},
    {"Alley 02", "Visit alley #2: finds location clues"},
    {"Office 03", "Visit office #3: finds location clues"},
    {"Pier 04", "Visit pier #4: finds location clues"},
    {"Library 05", "Visit library #5: finds location clues"},
    {"Depot 06", "Visit depot #6: finds location clues"},
    {"Diner 07", "Visit diner #7: finds location clues"},
    {"Alley 08", "Visit alley #8: finds location clues"},
    {"Office 09", "Visit office #9: finds location clues"},
    {"Pier 10", "Visit pier #10: finds location clues"},
    {"Library 11", "Visit library #11: finds location clues"},
    {"Depot 12", "Visit depot #12: finds location clues"},
};

static const CardputerGameCore::NamedValue POCKET_DETECTIVE_AGENCY_ROWS_3[] = {
    {"Alibi 01", "Ask alibi #1: marks statements and contradictions"},
    {"Debt 02", "Ask debt #2: marks statements and contradictions"},
    {"Noise 03", "Ask noise #3: marks statements and contradictions"},
    {"Receipt 04", "Ask receipt #4: marks statements and contradictions"},
    {"Key 05", "Ask key #5: marks statements and contradictions"},
    {"Motive 06", "Ask motive #6: marks statements and contradictions"},
    {"Witness 07", "Ask witness #7: marks statements and contradictions"},
    {"Time 08", "Ask time #8: marks statements and contradictions"},
    {"Alibi 09", "Ask alibi #9: marks statements and contradictions"},
    {"Debt 10", "Ask debt #10: marks statements and contradictions"},
    {"Noise 11", "Ask noise #11: marks statements and contradictions"},
    {"Receipt 12", "Ask receipt #12: marks statements and contradictions"},
    {"Key 13", "Ask key #13: marks statements and contradictions"},
    {"Motive 14", "Ask motive #14: marks statements and contradictions"},
    {"Witness 15", "Ask witness #15: marks statements and contradictions"},
    {"Time 16", "Ask time #16: marks statements and contradictions"},
    {"Alibi 17", "Ask alibi #17: marks statements and contradictions"},
    {"Debt 18", "Ask debt #18: marks statements and contradictions"},
    {"Noise 19", "Ask noise #19: marks statements and contradictions"},
    {"Receipt 20", "Ask receipt #20: marks statements and contradictions"},
    {"Key 21", "Ask key #21: marks statements and contradictions"},
    {"Motive 22", "Ask motive #22: marks statements and contradictions"},
    {"Witness 23", "Ask witness #23: marks statements and contradictions"},
    {"Time 24", "Ask time #24: marks statements and contradictions"},
    {"Alibi 25", "Ask alibi #25: marks statements and contradictions"},
    {"Debt 26", "Ask debt #26: marks statements and contradictions"},
    {"Noise 27", "Ask noise #27: marks statements and contradictions"},
    {"Receipt 28", "Ask receipt #28: marks statements and contradictions"},
    {"Key 29", "Ask key #29: marks statements and contradictions"},
    {"Motive 30", "Ask motive #30: marks statements and contradictions"},
    {"Witness 31", "Ask witness #31: marks statements and contradictions"},
    {"Time 32", "Ask time #32: marks statements and contradictions"},
    {"Alibi 33", "Ask alibi #33: marks statements and contradictions"},
    {"Debt 34", "Ask debt #34: marks statements and contradictions"},
    {"Noise 35", "Ask noise #35: marks statements and contradictions"},
    {"Receipt 36", "Ask receipt #36: marks statements and contradictions"},
    {"Key 37", "Ask key #37: marks statements and contradictions"},
    {"Motive 38", "Ask motive #38: marks statements and contradictions"},
    {"Witness 39", "Ask witness #39: marks statements and contradictions"},
    {"Time 40", "Ask time #40: marks statements and contradictions"},
    {"Alibi 41", "Ask alibi #41: marks statements and contradictions"},
    {"Debt 42", "Ask debt #42: marks statements and contradictions"},
    {"Noise 43", "Ask noise #43: marks statements and contradictions"},
    {"Receipt 44", "Ask receipt #44: marks statements and contradictions"},
    {"Key 45", "Ask key #45: marks statements and contradictions"},
    {"Motive 46", "Ask motive #46: marks statements and contradictions"},
    {"Witness 47", "Ask witness #47: marks statements and contradictions"},
    {"Time 48", "Ask time #48: marks statements and contradictions"},
};

static const CardputerGameCore::NamedValue POCKET_DETECTIVE_AGENCY_ROWS_4[] = {
    {"Receipt 01", "Read receipt #1: reviews discovered proof"},
    {"Footprint 02", "Read footprint #2: reviews discovered proof"},
    {"Photo 03", "Read photo #3: reviews discovered proof"},
    {"Ledger 04", "Read ledger #4: reviews discovered proof"},
    {"Key 05", "Read key #5: reviews discovered proof"},
    {"Thread 06", "Read thread #6: reviews discovered proof"},
    {"Ticket 07", "Read ticket #7: reviews discovered proof"},
    {"Note 08", "Read note #8: reviews discovered proof"},
    {"Receipt 09", "Read receipt #9: reviews discovered proof"},
    {"Footprint 10", "Read footprint #10: reviews discovered proof"},
    {"Photo 11", "Read photo #11: reviews discovered proof"},
    {"Ledger 12", "Read ledger #12: reviews discovered proof"},
    {"Key 13", "Read key #13: reviews discovered proof"},
    {"Thread 14", "Read thread #14: reviews discovered proof"},
    {"Ticket 15", "Read ticket #15: reviews discovered proof"},
    {"Note 16", "Read note #16: reviews discovered proof"},
    {"Receipt 17", "Read receipt #17: reviews discovered proof"},
    {"Footprint 18", "Read footprint #18: reviews discovered proof"},
    {"Photo 19", "Read photo #19: reviews discovered proof"},
    {"Ledger 20", "Read ledger #20: reviews discovered proof"},
    {"Key 21", "Read key #21: reviews discovered proof"},
    {"Thread 22", "Read thread #22: reviews discovered proof"},
    {"Ticket 23", "Read ticket #23: reviews discovered proof"},
    {"Note 24", "Read note #24: reviews discovered proof"},
    {"Receipt 25", "Read receipt #25: reviews discovered proof"},
    {"Footprint 26", "Read footprint #26: reviews discovered proof"},
    {"Photo 27", "Read photo #27: reviews discovered proof"},
    {"Ledger 28", "Read ledger #28: reviews discovered proof"},
    {"Key 29", "Read key #29: reviews discovered proof"},
    {"Thread 30", "Read thread #30: reviews discovered proof"},
    {"Ticket 31", "Read ticket #31: reviews discovered proof"},
    {"Note 32", "Read note #32: reviews discovered proof"},
    {"Receipt 33", "Read receipt #33: reviews discovered proof"},
    {"Footprint 34", "Read footprint #34: reviews discovered proof"},
    {"Photo 35", "Read photo #35: reviews discovered proof"},
    {"Ledger 36", "Read ledger #36: reviews discovered proof"},
    {"Key 37", "Read key #37: reviews discovered proof"},
    {"Thread 38", "Read thread #38: reviews discovered proof"},
    {"Ticket 39", "Read ticket #39: reviews discovered proof"},
    {"Note 40", "Read note #40: reviews discovered proof"},
};

static const CardputerGameCore::NamedValue POCKET_DETECTIVE_AGENCY_ROWS_5[] = {
    {"Receipt+Alibi 01", "Link receipt+alibi #1: creates notebook link tokens"},
    {"Photo+Time 02", "Link photo+time #2: creates notebook link tokens"},
    {"Key+Door 03", "Link key+door #3: creates notebook link tokens"},
    {"Ledger+Debt 04", "Link ledger+debt #4: creates notebook link tokens"},
    {"Ticket+Pier 05", "Link ticket+pier #5: creates notebook link tokens"},
    {"Thread+Coat 06", "Link thread+coat #6: creates notebook link tokens"},
    {"Receipt+Alibi 07", "Link receipt+alibi #7: creates notebook link tokens"},
    {"Photo+Time 08", "Link photo+time #8: creates notebook link tokens"},
    {"Key+Door 09", "Link key+door #9: creates notebook link tokens"},
    {"Ledger+Debt 10", "Link ledger+debt #10: creates notebook link tokens"},
    {"Ticket+Pier 11", "Link ticket+pier #11: creates notebook link tokens"},
    {"Thread+Coat 12", "Link thread+coat #12: creates notebook link tokens"},
    {"Receipt+Alibi 13", "Link receipt+alibi #13: creates notebook link tokens"},
    {"Photo+Time 14", "Link photo+time #14: creates notebook link tokens"},
    {"Key+Door 15", "Link key+door #15: creates notebook link tokens"},
    {"Ledger+Debt 16", "Link ledger+debt #16: creates notebook link tokens"},
    {"Ticket+Pier 17", "Link ticket+pier #17: creates notebook link tokens"},
    {"Thread+Coat 18", "Link thread+coat #18: creates notebook link tokens"},
};

static const CardputerGameCore::NamedValue POCKET_DETECTIVE_AGENCY_ROWS_6[] = {
    {"Full Truth 01", "Close full truth #1: resolves accusation path"},
    {"Partial 02", "Close partial #2: resolves accusation path"},
    {"Wrong Lead 03", "Close wrong lead #3: resolves accusation path"},
    {"Coverup 04", "Close coverup #4: resolves accusation path"},
    {"Full Truth 05", "Close full truth #5: resolves accusation path"},
    {"Partial 06", "Close partial #6: resolves accusation path"},
    {"Wrong Lead 07", "Close wrong lead #7: resolves accusation path"},
    {"Coverup 08", "Close coverup #8: resolves accusation path"},
    {"Full Truth 09", "Close full truth #9: resolves accusation path"},
    {"Partial 10", "Close partial #10: resolves accusation path"},
    {"Wrong Lead 11", "Close wrong lead #11: resolves accusation path"},
    {"Coverup 12", "Close coverup #12: resolves accusation path"},
};

static const CardputerGameCore::DeepScreenDef SCREENS[] = {
    {"AGENCY", "Open", POCKET_DETECTIVE_AGENCY_ROWS_0, 4, {2, -1, 1, 1, 1, 1, 0, 0}, 3, 0, 1UL},
    {"CASE FILE", "Study", POCKET_DETECTIVE_AGENCY_ROWS_1, 12, {0, -1, 1, 0, 1, 1, 0, 0}, 2, 1, 2UL},
    {"MAP", "Visit", POCKET_DETECTIVE_AGENCY_ROWS_2, 12, {-1, -2, 1, 1, 2, 1, 0, 0}, 4, 2, 4UL},
    {"INTERVIEW", "Ask", POCKET_DETECTIVE_AGENCY_ROWS_3, 48, {-1, -2, 1, 2, 1, 2, 0, 0}, 4, 3, 8UL},
    {"CLUE BOOK", "Read", POCKET_DETECTIVE_AGENCY_ROWS_4, 40, {0, 0, 1, 0, 1, 1, 0, 0}, 2, 4, 16UL},
    {"COMPARE", "Link", POCKET_DETECTIVE_AGENCY_ROWS_5, 18, {0, -1, 2, -1, 2, 2, 0, 0}, 5, 5, 32UL},
    {"ACCUSE", "Close", POCKET_DETECTIVE_AGENCY_ROWS_6, 12, {8, -4, 3, 4, 2, 1, 0, 0}, 7, 6, 64UL},
};

static const CardputerGameCore::NamedValue EVENTS[] = {
    {"Pressure 01", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Choice 02", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Discovery 03", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Trouble 04", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Favor 05", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Warning 06", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Breakthrough 07", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Setback 08", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Pressure 09", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Choice 10", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Discovery 11", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Trouble 12", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Favor 13", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Warning 14", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Breakthrough 15", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Setback 16", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Pressure 17", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Choice 18", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Discovery 19", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Trouble 20", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Favor 21", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Warning 22", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Breakthrough 23", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Setback 24", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Pressure 25", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Choice 26", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Discovery 27", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Trouble 28", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Favor 29", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Warning 30", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Breakthrough 31", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Setback 32", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Pressure 33", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Choice 34", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Discovery 35", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Trouble 36", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Favor 37", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Warning 38", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Breakthrough 39", "A bespoke Pocket Detective event changes saved state and story flags."},
    {"Setback 40", "A bespoke Pocket Detective event changes saved state and story flags."},
};

static const CardputerGameCore::NamedValue ENDINGS[] = {
    {"Honest Agency", "Ending path 1: resources, flags, and reputation decide this outcome."},
    {"Famous Sleuth", "Ending path 2: resources, flags, and reputation decide this outcome."},
    {"Quiet Fixer", "Ending path 3: resources, flags, and reputation decide this outcome."},
    {"Cold File", "Ending path 4: resources, flags, and reputation decide this outcome."},
    {"Wrong Arrest", "Ending path 5: resources, flags, and reputation decide this outcome."},
    {"True Case", "Ending path 6: resources, flags, and reputation decide this outcome."},
};

static const CardputerGameCore::DeepGameDefinition DEF = {
    "Pocket Detective",
    "pocket-detective-agency",
    "Notebook mystery campaign",
    "PDA2",
    RESOURCES,
    sizeof(RESOURCES) / sizeof(RESOURCES[0]),
    SCREENS,
    sizeof(SCREENS) / sizeof(SCREENS[0]),
    EVENTS,
    sizeof(EVENTS) / sizeof(EVENTS[0]),
    ENDINGS,
    sizeof(ENDINGS) / sizeof(ENDINGS[0]),
    150,
    0xFFFF,
    0xFD20
};

const CardputerGameCore::DeepGameDefinition& gameDefinition() {
  return DEF;
}
