#include "GameData.h"

static const CardputerGameCore::ResourceDef RESOURCES[] = {
    {"Gold", 35, 0, 999, 5, -2},
    {"Food", 8, 0, 50, -1, 3},
    {"Stam", 80, 0, 100, -6, 12},
    {"Stress", 8, 0, 100, 4, -8},
    {"Pack", 100, 0, 100, -5, 4},
    {"Stamp", 0, 0, 99, 2, 0},
    {"Susp", 0, 0, 100, 3, -2},
    {"Wound", 0, 0, 9, 1, -1},
};

static const CardputerGameCore::NamedValue DUNGEON_COURIER_ROWS_0[] = {
    {"Root 01", "Work root #1: updates local faction mood"},
    {"Bell 02", "Work bell #2: updates local faction mood"},
    {"Moss 03", "Work moss #3: updates local faction mood"},
    {"Ash 04", "Work ash #4: updates local faction mood"},
    {"Glass 05", "Work glass #5: updates local faction mood"},
    {"Rune 06", "Work rune #6: updates local faction mood"},
    {"Ledger 07", "Work ledger #7: updates local faction mood"},
    {"Moon 08", "Work moon #8: updates local faction mood"},
    {"Crown 09", "Work crown #9: updates local faction mood"},
};

static const CardputerGameCore::NamedValue DUNGEON_COURIER_ROWS_1[] = {
    {"Candle 01", "Take candle #1: sets one active delivery job"},
    {"Ledger 02", "Take ledger #2: sets one active delivery job"},
    {"Crown 03", "Take crown #3: sets one active delivery job"},
    {"Witch 04", "Take witch #4: sets one active delivery job"},
    {"Vault 05", "Take vault #5: sets one active delivery job"},
    {"Moon 06", "Take moon #6: sets one active delivery job"},
    {"Lock 07", "Take lock #7: sets one active delivery job"},
    {"River 08", "Take river #8: sets one active delivery job"},
    {"Ash 09", "Take ash #9: sets one active delivery job"},
    {"Root 10", "Take root #10: sets one active delivery job"},
    {"Bell 11", "Take bell #11: sets one active delivery job"},
    {"Moss 12", "Take moss #12: sets one active delivery job"},
    {"Candle 13", "Take candle #13: sets one active delivery job"},
    {"Ledger 14", "Take ledger #14: sets one active delivery job"},
    {"Crown 15", "Take crown #15: sets one active delivery job"},
    {"Witch 16", "Take witch #16: sets one active delivery job"},
    {"Vault 17", "Take vault #17: sets one active delivery job"},
    {"Moon 18", "Take moon #18: sets one active delivery job"},
    {"Lock 19", "Take lock #19: sets one active delivery job"},
    {"River 20", "Take river #20: sets one active delivery job"},
    {"Ash 21", "Take ash #21: sets one active delivery job"},
    {"Root 22", "Take root #22: sets one active delivery job"},
    {"Bell 23", "Take bell #23: sets one active delivery job"},
    {"Moss 24", "Take moss #24: sets one active delivery job"},
    {"Candle 25", "Take candle #25: sets one active delivery job"},
    {"Ledger 26", "Take ledger #26: sets one active delivery job"},
    {"Crown 27", "Take crown #27: sets one active delivery job"},
    {"Witch 28", "Take witch #28: sets one active delivery job"},
    {"Vault 29", "Take vault #29: sets one active delivery job"},
    {"Moon 30", "Take moon #30: sets one active delivery job"},
    {"Lock 31", "Take lock #31: sets one active delivery job"},
    {"River 32", "Take river #32: sets one active delivery job"},
    {"Ash 33", "Take ash #33: sets one active delivery job"},
    {"Root 34", "Take root #34: sets one active delivery job"},
    {"Bell 35", "Take bell #35: sets one active delivery job"},
    {"Moss 36", "Take moss #36: sets one active delivery job"},
};

static const CardputerGameCore::NamedValue DUNGEON_COURIER_ROWS_2[] = {
    {"Food 01", "Pack food #1: prepares for route choices"},
    {"Torch 02", "Pack torch #2: prepares for route choices"},
    {"Bandage 03", "Pack bandage #3: prepares for route choices"},
    {"Charm 04", "Pack charm #4: prepares for route choices"},
    {"Rope 05", "Pack rope #5: prepares for route choices"},
    {"Seal 06", "Pack seal #6: prepares for route choices"},
    {"Map 07", "Pack map #7: prepares for route choices"},
    {"Ink 08", "Pack ink #8: prepares for route choices"},
    {"Food 09", "Pack food #9: prepares for route choices"},
    {"Torch 10", "Pack torch #10: prepares for route choices"},
    {"Bandage 11", "Pack bandage #11: prepares for route choices"},
    {"Charm 12", "Pack charm #12: prepares for route choices"},
    {"Rope 13", "Pack rope #13: prepares for route choices"},
    {"Seal 14", "Pack seal #14: prepares for route choices"},
    {"Map 15", "Pack map #15: prepares for route choices"},
    {"Ink 16", "Pack ink #16: prepares for route choices"},
};

static const CardputerGameCore::NamedValue DUNGEON_COURIER_ROWS_3[] = {
    {"Safe 01", "Run safe #1: consumes supplies and deadline"},
    {"Common 02", "Run common #2: consumes supplies and deadline"},
    {"Shortcut 03", "Run shortcut #3: consumes supplies and deadline"},
    {"Ferry 04", "Run ferry #4: consumes supplies and deadline"},
    {"Crypt 05", "Run crypt #5: consumes supplies and deadline"},
    {"Lift 06", "Run lift #6: consumes supplies and deadline"},
    {"Pantry 07", "Run pantry #7: consumes supplies and deadline"},
    {"Road 08", "Run road #8: consumes supplies and deadline"},
    {"Door 09", "Run door #9: consumes supplies and deadline"},
    {"Bridge 10", "Run bridge #10: consumes supplies and deadline"},
    {"Safe 11", "Run safe #11: consumes supplies and deadline"},
    {"Common 12", "Run common #12: consumes supplies and deadline"},
    {"Shortcut 13", "Run shortcut #13: consumes supplies and deadline"},
    {"Ferry 14", "Run ferry #14: consumes supplies and deadline"},
    {"Crypt 15", "Run crypt #15: consumes supplies and deadline"},
};

static const CardputerGameCore::NamedValue DUNGEON_COURIER_ROWS_4[] = {
    {"Toll 01", "Choose toll #1: changes integrity and reputation"},
    {"Rain 02", "Choose rain #2: changes integrity and reputation"},
    {"Rival 03", "Choose rival #3: changes integrity and reputation"},
    {"Wrong Door 04", "Choose wrong door #4: changes integrity and reputation"},
    {"Bandit 05", "Choose bandit #5: changes integrity and reputation"},
    {"Charm 06", "Choose charm #6: changes integrity and reputation"},
    {"Open Box 07", "Choose open box #7: changes integrity and reputation"},
    {"Signature 08", "Choose signature #8: changes integrity and reputation"},
    {"Toll 09", "Choose toll #9: changes integrity and reputation"},
    {"Rain 10", "Choose rain #10: changes integrity and reputation"},
    {"Rival 11", "Choose rival #11: changes integrity and reputation"},
    {"Wrong Door 12", "Choose wrong door #12: changes integrity and reputation"},
    {"Bandit 13", "Choose bandit #13: changes integrity and reputation"},
    {"Charm 14", "Choose charm #14: changes integrity and reputation"},
    {"Open Box 15", "Choose open box #15: changes integrity and reputation"},
    {"Signature 16", "Choose signature #16: changes integrity and reputation"},
    {"Toll 17", "Choose toll #17: changes integrity and reputation"},
    {"Rain 18", "Choose rain #18: changes integrity and reputation"},
    {"Rival 19", "Choose rival #19: changes integrity and reputation"},
    {"Wrong Door 20", "Choose wrong door #20: changes integrity and reputation"},
    {"Bandit 21", "Choose bandit #21: changes integrity and reputation"},
    {"Charm 22", "Choose charm #22: changes integrity and reputation"},
    {"Open Box 23", "Choose open box #23: changes integrity and reputation"},
    {"Signature 24", "Choose signature #24: changes integrity and reputation"},
    {"Toll 25", "Choose toll #25: changes integrity and reputation"},
    {"Rain 26", "Choose rain #26: changes integrity and reputation"},
    {"Rival 27", "Choose rival #27: changes integrity and reputation"},
    {"Wrong Door 28", "Choose wrong door #28: changes integrity and reputation"},
    {"Bandit 29", "Choose bandit #29: changes integrity and reputation"},
    {"Charm 30", "Choose charm #30: changes integrity and reputation"},
    {"Open Box 31", "Choose open box #31: changes integrity and reputation"},
    {"Signature 32", "Choose signature #32: changes integrity and reputation"},
    {"Toll 33", "Choose toll #33: changes integrity and reputation"},
    {"Rain 34", "Choose rain #34: changes integrity and reputation"},
    {"Rival 35", "Choose rival #35: changes integrity and reputation"},
    {"Wrong Door 36", "Choose wrong door #36: changes integrity and reputation"},
    {"Bandit 37", "Choose bandit #37: changes integrity and reputation"},
    {"Charm 38", "Choose charm #38: changes integrity and reputation"},
    {"Open Box 39", "Choose open box #39: changes integrity and reputation"},
    {"Signature 40", "Choose signature #40: changes integrity and reputation"},
    {"Toll 41", "Choose toll #41: changes integrity and reputation"},
    {"Rain 42", "Choose rain #42: changes integrity and reputation"},
    {"Rival 43", "Choose rival #43: changes integrity and reputation"},
    {"Wrong Door 44", "Choose wrong door #44: changes integrity and reputation"},
    {"Bandit 45", "Choose bandit #45: changes integrity and reputation"},
    {"Charm 46", "Choose charm #46: changes integrity and reputation"},
    {"Open Box 47", "Choose open box #47: changes integrity and reputation"},
    {"Signature 48", "Choose signature #48: changes integrity and reputation"},
};

static const CardputerGameCore::NamedValue DUNGEON_COURIER_ROWS_5[] = {
    {"Clean 01", "Close clean #1: pays based on package state"},
    {"Late 02", "Close late #2: pays based on package state"},
    {"Damaged 03", "Close damaged #3: pays based on package state"},
    {"Opened 04", "Close opened #4: pays based on package state"},
    {"Fake Seal 05", "Close fake seal #5: pays based on package state"},
    {"Bonus 06", "Close bonus #6: pays based on package state"},
    {"Rival 07", "Close rival #7: pays based on package state"},
    {"Secret 08", "Close secret #8: pays based on package state"},
    {"Clean 09", "Close clean #9: pays based on package state"},
    {"Late 10", "Close late #10: pays based on package state"},
    {"Damaged 11", "Close damaged #11: pays based on package state"},
    {"Opened 12", "Close opened #12: pays based on package state"},
};

static const CardputerGameCore::NamedValue DUNGEON_COURIER_ROWS_6[] = {
    {"Route Memory 01", "Train route memory #1: spends stamps for a courier edge"},
    {"Steady Hands 02", "Train steady hands #2: spends stamps for a courier edge"},
    {"Silver Tongue 03", "Train silver tongue #3: spends stamps for a courier edge"},
    {"Medic 04", "Train medic #4: spends stamps for a courier edge"},
    {"Lucky Stamp 05", "Train lucky stamp #5: spends stamps for a courier edge"},
    {"Night Eye 06", "Train night eye #6: spends stamps for a courier edge"},
    {"Hard Boots 07", "Train hard boots #7: spends stamps for a courier edge"},
    {"Ledger 08", "Train ledger #8: spends stamps for a courier edge"},
    {"Calm 09", "Train calm #9: spends stamps for a courier edge"},
    {"Shortcut 10", "Train shortcut #10: spends stamps for a courier edge"},
};

static const CardputerGameCore::DeepScreenDef SCREENS[] = {
    {"TOWN", "Visit", DUNGEON_COURIER_ROWS_0, 9, {2, 1, 4, -2, 0, 1, -1, -1}, 3, 0, 1UL},
    {"BOARD", "Accept", DUNGEON_COURIER_ROWS_1, 36, {6, -1, -3, 2, -3, 1, 1, 0}, 5, 1, 2UL},
    {"PACK", "Buy", DUNGEON_COURIER_ROWS_2, 16, {-2, 2, 2, -1, 2, 0, -1, -1}, 3, 2, 4UL},
    {"ROUTE", "Travel", DUNGEON_COURIER_ROWS_3, 15, {4, -2, -7, 3, -4, 1, 1, 1}, 5, 3, 8UL},
    {"EVENT", "Resolve", DUNGEON_COURIER_ROWS_4, 48, {3, -1, -2, 2, -5, 1, 2, 1}, 4, 4, 16UL},
    {"DELIVERY", "Deliver", DUNGEON_COURIER_ROWS_5, 12, {10, 0, 4, -3, -4, 2, -2, -1}, 7, 5, 32UL},
    {"PERKS", "Learn", DUNGEON_COURIER_ROWS_6, 10, {-6, 0, 2, -2, 2, -3, -1, -1}, 4, 6, 64UL},
};

static const CardputerGameCore::NamedValue EVENTS[] = {
    {"Pressure 01", "A bespoke Dungeon Courier event changes saved state and story flags."},
    {"Choice 02", "A bespoke Dungeon Courier event changes saved state and story flags."},
    {"Discovery 03", "A bespoke Dungeon Courier event changes saved state and story flags."},
    {"Trouble 04", "A bespoke Dungeon Courier event changes saved state and story flags."},
    {"Favor 05", "A bespoke Dungeon Courier event changes saved state and story flags."},
    {"Warning 06", "A bespoke Dungeon Courier event changes saved state and story flags."},
    {"Breakthrough 07", "A bespoke Dungeon Courier event changes saved state and story flags."},
    {"Setback 08", "A bespoke Dungeon Courier event changes saved state and story flags."},
    {"Pressure 09", "A bespoke Dungeon Courier event changes saved state and story flags."},
    {"Choice 10", "A bespoke Dungeon Courier event changes saved state and story flags."},
    {"Discovery 11", "A bespoke Dungeon Courier event changes saved state and story flags."},
    {"Trouble 12", "A bespoke Dungeon Courier event changes saved state and story flags."},
    {"Favor 13", "A bespoke Dungeon Courier event changes saved state and story flags."},
    {"Warning 14", "A bespoke Dungeon Courier event changes saved state and story flags."},
    {"Breakthrough 15", "A bespoke Dungeon Courier event changes saved state and story flags."},
    {"Setback 16", "A bespoke Dungeon Courier event changes saved state and story flags."},
    {"Pressure 17", "A bespoke Dungeon Courier event changes saved state and story flags."},
    {"Choice 18", "A bespoke Dungeon Courier event changes saved state and story flags."},
};

static const CardputerGameCore::NamedValue ENDINGS[] = {
    {"Legend Run", "Ending path 1: resources, flags, and reputation decide this outcome."},
    {"Hard Truth", "Ending path 2: resources, flags, and reputation decide this outcome."},
    {"Quiet Win", "Ending path 3: resources, flags, and reputation decide this outcome."},
    {"Faction Path", "Ending path 4: resources, flags, and reputation decide this outcome."},
    {"Costly Deal", "Ending path 5: resources, flags, and reputation decide this outcome."},
    {"Run Failed", "Ending path 6: resources, flags, and reputation decide this outcome."},
};

static const CardputerGameCore::DeepGameDefinition DEF = {
    "Dungeon Courier",
    "dungeon-courier",
    "Contract delivery RPG",
    "DCR2",
    RESOURCES,
    sizeof(RESOURCES) / sizeof(RESOURCES[0]),
    SCREENS,
    sizeof(SCREENS) / sizeof(SCREENS[0]),
    EVENTS,
    sizeof(EVENTS) / sizeof(EVENTS[0]),
    ENDINGS,
    sizeof(ENDINGS) / sizeof(ENDINGS[0]),
    160,
    0xB81F,
    0xFD20
};

const CardputerGameCore::DeepGameDefinition& gameDefinition() {
  return DEF;
}
