#include "GameData.h"

static const CardputerGameCore::ResourceDef RESOURCES[] = {
    {"Gold", 70, 0, 999, 5, -4},
    {"Fame", 5, 0, 999, 3, 0},
    {"Food", 35, 0, 120, -2, 5},
    {"Stress", 10, 0, 100, 5, -6},
    {"Injury", 0, 0, 100, 2, -4},
    {"Rank", 1, 0, 9, 1, 0},
    {"Trust", 45, 0, 100, 1, 2},
    {"Renown", 0, 0, 99, 1, 0},
};

static const CardputerGameCore::NamedValue GUILDMASTER_POCKET_ROWS_0[] = {
    {"Hall 01", "Manage hall #1: sets weekly guild pressure"},
    {"Client 02", "Manage client #2: sets weekly guild pressure"},
    {"Region 03", "Manage region #3: sets weekly guild pressure"},
    {"Supply 04", "Manage supply #4: sets weekly guild pressure"},
    {"Charter 05", "Manage charter #5: sets weekly guild pressure"},
    {"Hall 06", "Manage hall #6: sets weekly guild pressure"},
    {"Client 07", "Manage client #7: sets weekly guild pressure"},
    {"Region 08", "Manage region #8: sets weekly guild pressure"},
    {"Supply 09", "Manage supply #9: sets weekly guild pressure"},
    {"Charter 10", "Manage charter #10: sets weekly guild pressure"},
};

static const CardputerGameCore::NamedValue GUILDMASTER_POCKET_ROWS_1[] = {
    {"Rat Cellar 01", "Quest rat cellar #1: runs a staged contract"},
    {"Moss Road 02", "Quest moss road #2: runs a staged contract"},
    {"Coin Vault 03", "Quest coin vault #3: runs a staged contract"},
    {"Moon Mine 04", "Quest moon mine #4: runs a staged contract"},
    {"Ash Keep 05", "Quest ash keep #5: runs a staged contract"},
    {"Frost Gate 06", "Quest frost gate #6: runs a staged contract"},
    {"Signal Ruin 07", "Quest signal ruin #7: runs a staged contract"},
    {"Baron Road 08", "Quest baron road #8: runs a staged contract"},
    {"Rat Cellar 09", "Quest rat cellar #9: runs a staged contract"},
    {"Moss Road 10", "Quest moss road #10: runs a staged contract"},
    {"Coin Vault 11", "Quest coin vault #11: runs a staged contract"},
    {"Moon Mine 12", "Quest moon mine #12: runs a staged contract"},
    {"Ash Keep 13", "Quest ash keep #13: runs a staged contract"},
    {"Frost Gate 14", "Quest frost gate #14: runs a staged contract"},
    {"Signal Ruin 15", "Quest signal ruin #15: runs a staged contract"},
    {"Baron Road 16", "Quest baron road #16: runs a staged contract"},
    {"Rat Cellar 17", "Quest rat cellar #17: runs a staged contract"},
    {"Moss Road 18", "Quest moss road #18: runs a staged contract"},
    {"Coin Vault 19", "Quest coin vault #19: runs a staged contract"},
    {"Moon Mine 20", "Quest moon mine #20: runs a staged contract"},
    {"Ash Keep 21", "Quest ash keep #21: runs a staged contract"},
    {"Frost Gate 22", "Quest frost gate #22: runs a staged contract"},
    {"Signal Ruin 23", "Quest signal ruin #23: runs a staged contract"},
    {"Baron Road 24", "Quest baron road #24: runs a staged contract"},
};

static const CardputerGameCore::NamedValue GUILDMASTER_POCKET_ROWS_2[] = {
    {"Fighter 01", "Pick fighter #1: sets class coverage"},
    {"Scout 02", "Pick scout #2: sets class coverage"},
    {"Medic 03", "Pick medic #3: sets class coverage"},
    {"Mage 04", "Pick mage #4: sets class coverage"},
    {"Guard 05", "Pick guard #5: sets class coverage"},
    {"Bard 06", "Pick bard #6: sets class coverage"},
    {"Engineer 07", "Pick engineer #7: sets class coverage"},
    {"Mystic 08", "Pick mystic #8: sets class coverage"},
};

static const CardputerGameCore::NamedValue GUILDMASTER_POCKET_ROWS_3[] = {
    {"Fighter 01", "Train fighter #1: improves class lane state"},
    {"Scout 02", "Train scout #2: improves class lane state"},
    {"Medic 03", "Train medic #3: improves class lane state"},
    {"Mage 04", "Train mage #4: improves class lane state"},
    {"Guard 05", "Train guard #5: improves class lane state"},
    {"Bard 06", "Train bard #6: improves class lane state"},
    {"Engineer 07", "Train engineer #7: improves class lane state"},
    {"Mystic 08", "Train mystic #8: improves class lane state"},
};

static const CardputerGameCore::NamedValue GUILDMASTER_POCKET_ROWS_4[] = {
    {"Combat 01", "Resolve combat #1: applies role checks and consequences"},
    {"Trap 02", "Resolve trap #2: applies role checks and consequences"},
    {"Social 03", "Resolve social #3: applies role checks and consequences"},
    {"Travel 04", "Resolve travel #4: applies role checks and consequences"},
    {"Weird 05", "Resolve weird #5: applies role checks and consequences"},
    {"Boss 06", "Resolve boss #6: applies role checks and consequences"},
    {"Escort 07", "Resolve escort #7: applies role checks and consequences"},
    {"Rescue 08", "Resolve rescue #8: applies role checks and consequences"},
    {"Combat 09", "Resolve combat #9: applies role checks and consequences"},
    {"Trap 10", "Resolve trap #10: applies role checks and consequences"},
    {"Social 11", "Resolve social #11: applies role checks and consequences"},
    {"Travel 12", "Resolve travel #12: applies role checks and consequences"},
    {"Weird 13", "Resolve weird #13: applies role checks and consequences"},
    {"Boss 14", "Resolve boss #14: applies role checks and consequences"},
    {"Escort 15", "Resolve escort #15: applies role checks and consequences"},
    {"Rescue 16", "Resolve rescue #16: applies role checks and consequences"},
    {"Combat 17", "Resolve combat #17: applies role checks and consequences"},
    {"Trap 18", "Resolve trap #18: applies role checks and consequences"},
    {"Social 19", "Resolve social #19: applies role checks and consequences"},
    {"Travel 20", "Resolve travel #20: applies role checks and consequences"},
    {"Weird 21", "Resolve weird #21: applies role checks and consequences"},
    {"Boss 22", "Resolve boss #22: applies role checks and consequences"},
    {"Escort 23", "Resolve escort #23: applies role checks and consequences"},
    {"Rescue 24", "Resolve rescue #24: applies role checks and consequences"},
    {"Combat 25", "Resolve combat #25: applies role checks and consequences"},
    {"Trap 26", "Resolve trap #26: applies role checks and consequences"},
    {"Social 27", "Resolve social #27: applies role checks and consequences"},
    {"Travel 28", "Resolve travel #28: applies role checks and consequences"},
    {"Weird 29", "Resolve weird #29: applies role checks and consequences"},
    {"Boss 30", "Resolve boss #30: applies role checks and consequences"},
    {"Escort 31", "Resolve escort #31: applies role checks and consequences"},
    {"Rescue 32", "Resolve rescue #32: applies role checks and consequences"},
};

static const CardputerGameCore::NamedValue GUILDMASTER_POCKET_ROWS_5[] = {
    {"Infirmary 01", "Build infirmary #1: spends gold for hall levels"},
    {"Barracks 02", "Build barracks #2: spends gold for hall levels"},
    {"Library 03", "Build library #3: spends gold for hall levels"},
    {"Blacksmith 04", "Build blacksmith #4: spends gold for hall levels"},
    {"Map Room 05", "Build map room #5: spends gold for hall levels"},
    {"Trophy Wall 06", "Build trophy wall #6: spends gold for hall levels"},
    {"Infirmary 07", "Build infirmary #7: spends gold for hall levels"},
    {"Barracks 08", "Build barracks #8: spends gold for hall levels"},
    {"Library 09", "Build library #9: spends gold for hall levels"},
    {"Blacksmith 10", "Build blacksmith #10: spends gold for hall levels"},
    {"Map Room 11", "Build map room #11: spends gold for hall levels"},
    {"Trophy Wall 12", "Build trophy wall #12: spends gold for hall levels"},
    {"Infirmary 13", "Build infirmary #13: spends gold for hall levels"},
    {"Barracks 14", "Build barracks #14: spends gold for hall levels"},
    {"Library 15", "Build library #15: spends gold for hall levels"},
    {"Blacksmith 16", "Build blacksmith #16: spends gold for hall levels"},
    {"Map Room 17", "Build map room #17: spends gold for hall levels"},
    {"Trophy Wall 18", "Build trophy wall #18: spends gold for hall levels"},
};

static const CardputerGameCore::NamedValue GUILDMASTER_POCKET_ROWS_6[] = {
    {"Ivory Hall 01", "Answer ivory hall #1: changes rival pressure"},
    {"Red Ledger 02", "Answer red ledger #2: changes rival pressure"},
    {"Moon Seat 03", "Answer moon seat #3: changes rival pressure"},
    {"Ivory Hall 04", "Answer ivory hall #4: changes rival pressure"},
    {"Red Ledger 05", "Answer red ledger #5: changes rival pressure"},
    {"Moon Seat 06", "Answer moon seat #6: changes rival pressure"},
    {"Ivory Hall 07", "Answer ivory hall #7: changes rival pressure"},
    {"Red Ledger 08", "Answer red ledger #8: changes rival pressure"},
    {"Moon Seat 09", "Answer moon seat #9: changes rival pressure"},
    {"Ivory Hall 10", "Answer ivory hall #10: changes rival pressure"},
    {"Red Ledger 11", "Answer red ledger #11: changes rival pressure"},
    {"Moon Seat 12", "Answer moon seat #12: changes rival pressure"},
};

static const CardputerGameCore::DeepScreenDef SCREENS[] = {
    {"GUILD", "Manage", GUILDMASTER_POCKET_ROWS_0, 10, {2, 2, -1, -2, 1, 1, 2, 1}, 3, 0, 1UL},
    {"QUESTS", "Send", GUILDMASTER_POCKET_ROWS_1, 24, {8, 4, -2, 4, 2, 1, 1, 1}, 6, 1, 2UL},
    {"PARTY", "Pick", GUILDMASTER_POCKET_ROWS_2, 8, {-1, 1, -1, -1, -1, 0, 2, 1}, 3, 2, 4UL},
    {"ROSTER", "Train", GUILDMASTER_POCKET_ROWS_3, 8, {-3, 1, -1, -2, -1, 0, 2, 2}, 4, 3, 8UL},
    {"RESULT", "Resolve", GUILDMASTER_POCKET_ROWS_4, 32, {6, 3, -2, 5, 3, 1, -1, 2}, 5, 4, 16UL},
    {"HALL", "Build", GUILDMASTER_POCKET_ROWS_5, 18, {-8, 2, 1, -3, -2, 1, 2, 3}, 5, 5, 32UL},
    {"RIVALS", "Answer", GUILDMASTER_POCKET_ROWS_6, 12, {2, 2, 0, 1, 1, 0, -2, 1}, 3, 6, 64UL},
};

static const CardputerGameCore::NamedValue EVENTS[] = {
    {"Pressure 01", "A bespoke Guildmaster event changes saved state and story flags."},
    {"Choice 02", "A bespoke Guildmaster event changes saved state and story flags."},
    {"Discovery 03", "A bespoke Guildmaster event changes saved state and story flags."},
    {"Trouble 04", "A bespoke Guildmaster event changes saved state and story flags."},
    {"Favor 05", "A bespoke Guildmaster event changes saved state and story flags."},
    {"Warning 06", "A bespoke Guildmaster event changes saved state and story flags."},
    {"Breakthrough 07", "A bespoke Guildmaster event changes saved state and story flags."},
    {"Setback 08", "A bespoke Guildmaster event changes saved state and story flags."},
    {"Pressure 09", "A bespoke Guildmaster event changes saved state and story flags."},
    {"Choice 10", "A bespoke Guildmaster event changes saved state and story flags."},
    {"Discovery 11", "A bespoke Guildmaster event changes saved state and story flags."},
    {"Trouble 12", "A bespoke Guildmaster event changes saved state and story flags."},
    {"Favor 13", "A bespoke Guildmaster event changes saved state and story flags."},
    {"Warning 14", "A bespoke Guildmaster event changes saved state and story flags."},
    {"Breakthrough 15", "A bespoke Guildmaster event changes saved state and story flags."},
    {"Setback 16", "A bespoke Guildmaster event changes saved state and story flags."},
    {"Pressure 17", "A bespoke Guildmaster event changes saved state and story flags."},
    {"Choice 18", "A bespoke Guildmaster event changes saved state and story flags."},
    {"Discovery 19", "A bespoke Guildmaster event changes saved state and story flags."},
    {"Trouble 20", "A bespoke Guildmaster event changes saved state and story flags."},
    {"Favor 21", "A bespoke Guildmaster event changes saved state and story flags."},
    {"Warning 22", "A bespoke Guildmaster event changes saved state and story flags."},
    {"Breakthrough 23", "A bespoke Guildmaster event changes saved state and story flags."},
    {"Setback 24", "A bespoke Guildmaster event changes saved state and story flags."},
    {"Pressure 25", "A bespoke Guildmaster event changes saved state and story flags."},
    {"Choice 26", "A bespoke Guildmaster event changes saved state and story flags."},
    {"Discovery 27", "A bespoke Guildmaster event changes saved state and story flags."},
    {"Trouble 28", "A bespoke Guildmaster event changes saved state and story flags."},
    {"Favor 29", "A bespoke Guildmaster event changes saved state and story flags."},
    {"Warning 30", "A bespoke Guildmaster event changes saved state and story flags."},
    {"Breakthrough 31", "A bespoke Guildmaster event changes saved state and story flags."},
    {"Setback 32", "A bespoke Guildmaster event changes saved state and story flags."},
};

static const CardputerGameCore::NamedValue ENDINGS[] = {
    {"Great Guild", "Ending path 1: resources, flags, and reputation decide this outcome."},
    {"Hero Graveyard", "Ending path 2: resources, flags, and reputation decide this outcome."},
    {"Rival Merger", "Ending path 3: resources, flags, and reputation decide this outcome."},
    {"Quiet Hall", "Ending path 4: resources, flags, and reputation decide this outcome."},
    {"Treaty Desk", "Ending path 5: resources, flags, and reputation decide this outcome."},
    {"Bankrupt Hall", "Ending path 6: resources, flags, and reputation decide this outcome."},
};

static const CardputerGameCore::DeepGameDefinition DEF = {
    "Guildmaster",
    "guildmaster-pocket",
    "Tiny quest desk",
    "GMP2",
    RESOURCES,
    sizeof(RESOURCES) / sizeof(RESOURCES[0]),
    SCREENS,
    sizeof(SCREENS) / sizeof(SCREENS[0]),
    EVENTS,
    sizeof(EVENTS) / sizeof(EVENTS[0]),
    ENDINGS,
    sizeof(ENDINGS) / sizeof(ENDINGS[0]),
    175,
    0xA145,
    0xFD20
};

const CardputerGameCore::DeepGameDefinition& gameDefinition() {
  return DEF;
}
